test values: ./runTests.py -x
{'ndim': None, 'flat': None, 'dtype': 'i', 'seed': None, 'x': True, 'flatness': (False, False, False), 'new': False}
.........................E.......................................F....................F......................................F.....F.......E..............................F.......FF....F..FF...........F......F.....................................FF...F.FEEF.F........F.....F..EE.......E.F.....FF.FF.F.FF........F..FF...F..............F......F..........................E..............................F.FF.....F................F...F...........................E.........E..EEE.E.......EEE.E.EEE.........E...EE...........E...EF..F.unexpected array size: new_size=1, got array with arr_size=0
unexpected array size: new_size=1, got array with arr_size=0
unexpected array size: new_size=1, got array with arr_size=0
F..unexpected array size: new_size=1, got array with arr_size=0
unexpected array size: new_size=1, got array with arr_size=0
unexpected array size: new_size=1, got array with arr_size=0
FFFF..F.F..FFF...F..F..F..F....FF.....FFF.................F.......E......................................FF....F..F............F...........................
======================================================================
ERROR: testDerivation (unitTests.outerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 1000, in testDerivation
    out = numpy.outer(Da,Db).reshape((20,3,10,3))
ValueError: total size of new array must be unchanged

======================================================================
ERROR: testDerivation (unitTests.outerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 1000, in testDerivation
    out = numpy.outer(Da,Db).reshape((20,3,10,3))
ValueError: total size of new array must be unchanged

======================================================================
ERROR: testDerivation (unitTests.outerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 1000, in testDerivation
    out = numpy.outer(Da,Db).reshape((20,3,10,3))
ValueError: total size of new array must be unchanged

======================================================================
ERROR: testComplexPowers (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 341, in testComplexPowers
    self.assertFalse( self.A**self.K1/self.A**self.K2 == self.A**(self.K1-self.K2))
  File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
    return self*other**(-1)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1695, in _mvarMul
    result = (self*mvarA*mvarB+mvar*selfA*selfB)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1669, in _matrixMul
    vectors=self.vectors*matrix,
  File "/home/olpc/personal-projects/mvar/__init__.py", line 347, in __init__
    self.copy(self.square())
  File "/home/olpc/personal-projects/mvar/__init__.py", line 483, in square
    var=self.var,
  File "/home/olpc/personal-projects/mvar/square.py", line 74, in square
    (var,vectors) = _subSquare(vectors,var)
  File "/home/olpc/personal-projects/mvar/square.py", line 131, in _subSquare
    (val,vec)=eig(cov)
  File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 790, in eig
    _assertFinite(a)
  File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 118, in _assertFinite
    raise LinAlgError, "Array must not contain infs or NaNs"
LinAlgError: Array must not contain infs or NaNs

======================================================================
ERROR: testGivenScalar (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 430, in testGivenScalar
    a = self.A.given(index=0,value=1)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 961, in given
    vectors=vectors,
  File "/home/olpc/personal-projects/mvar/__init__.py", line 338, in __init__
    [1  ,mean   ],
  File "/home/olpc/personal-projects/mvar/helpers.py", line 170, in autostack
    for row in rows
  File "/usr/lib/python2.6/dist-packages/numpy/lib/shape_base.py", line 461, in vstack
    return _nx.concatenate(map(atleast_2d,tup),0)
ValueError: array dimensions must agree except for d_0

======================================================================
ERROR: testGivenVector (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 453, in testGivenVector
    self.assertTrue( mvar.givenVector(self.A,index=0,value=1)==self.A.given(index=0,value=1) )
  File "/home/olpc/personal-projects/mvar/__init__.py", line 961, in given
    vectors=vectors,
  File "/home/olpc/personal-projects/mvar/__init__.py", line 338, in __init__
    [1  ,mean   ],
  File "/home/olpc/personal-projects/mvar/helpers.py", line 170, in autostack
    for row in rows
  File "/usr/lib/python2.6/dist-packages/numpy/lib/shape_base.py", line 461, in vstack
    return _nx.concatenate(map(atleast_2d,tup),0)
ValueError: array dimensions must agree except for d_0

======================================================================
ERROR: testAnd (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 516, in testAnd
    measured[self.ndim:]=measurment
  File "/home/olpc/personal-projects/mvar/__init__.py", line 972, in __setitem__
    self.copy(self.given(index,value))
  File "/home/olpc/personal-projects/mvar/__init__.py", line 942, in given
    mean[:,fixed]=value.mean
IndexError: index (15) out of range (0<=index<14) in dimension 1

======================================================================
ERROR: testDerivation (unitTests.outerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 1000, in testDerivation
    out = numpy.outer(Da,Db).reshape((20,3,10,3))
ValueError: total size of new array must be unchanged

======================================================================
ERROR: testCov (unitTests.propertyTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 314, in testCov
    self.assertTrue( (self.A*self.B.transform() + self.B*self.A.transform()).cov/2 == (self.A*self.B).cov )
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testDiv (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 269, in testDiv
    self.assertTrue( self.A/self.B == self.A*(self.B**(-1)) )
  File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
    return self*other**(-1)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testMul (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 206, in testMul
    self.assertTrue( self.A**2==self.A*self.A )
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testMulTypes (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 198, in testMulTypes
    self.assertTrue( isinstance(self.A*self.B,Mvar) )
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testMvarMul (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 212, in testMvarMul
    self.assertTrue( (self.A*self.B).cov == (self.A*self.B.transform()+self.B*self.A.transform()).cov/2 )
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testDerivation (unitTests.innerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 967, in testDerivation
    (B*A.mean.H).trace() +
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testDerivation (unitTests.outerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 1000, in testDerivation
    out = numpy.outer(Da,Db).reshape((20,3,10,3))
ValueError: total size of new array must be unchanged

======================================================================
ERROR: testComplexPowers (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 340, in testComplexPowers
    self.assertFalse( self.A**self.K1*self.A**self.K2 == self.A**(self.K1+self.K2))
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testIntPowers (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 329, in testIntPowers
    self.assertTrue( self.A.transform(self.N)== self.A.transform()**self.N )
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 303, in __pow__
    return matrix_power(self, other)
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 130, in matrix_power
    M = inv(M)
  File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 355, in inv
    return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
  File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 258, in solve
    return wrap(b.transpose().astype(result_t))
ValueError: On entry to DGESV parameter number 4 had an illegal value

======================================================================
ERROR: testRealPow (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 386, in testRealPow
    self.assertTrue( self.A*self.A==self.A**2 )
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testZeroFlat (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 371, in testZeroFlat
    self.assertTrue( self.A**0 == self.A**(-1)*self.A )
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testZeroPow (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 365, in testZeroPow
    self.assertTrue( self.A**0*self.A==self.A )
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testRight (unitTests.commuteTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 30, in testRight
    self.assertTrue( self.A*self.B == self.B*self.A )
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testNotFlat (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 578, in testNotFlat
    self.assertTrue( self.A & self.B == mvar.wiki(self.A,self.B))
  File "/home/olpc/personal-projects/mvar/__init__.py", line 2078, in wiki
    Kk=P.cov*Sk.I
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 519, in getI
    return asmatrix(func(self))
  File "/usr/lib/python2.6/dist-packages/scipy/linalg/basic.py", line 366, in inv
    lu,piv,info = getrf(a1,overwrite_a=overwrite_a)
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)

======================================================================
ERROR: testGivenScalar (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 430, in testGivenScalar
    a = self.A.given(index=0,value=1)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 929, in given
    fixed=binindex(index,self.ndim)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 2162, in binindex
    binindex[index]=True
IndexError: index out of bounds

======================================================================
ERROR: testGivenVector (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 453, in testGivenVector
    self.assertTrue( mvar.givenVector(self.A,index=0,value=1)==self.A.given(index=0,value=1) )
  File "/home/olpc/personal-projects/mvar/__init__.py", line 2092, in givenVector
    fixed=binindex(index,self.ndim)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 2162, in binindex
    binindex[index]=True
IndexError: index out of bounds

======================================================================
ERROR: testDet (unitTests.linalgTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 407, in testDet
    self.assertTrue( Matrix(self.A.det())== numpy.linalg.det(self.A.cov) )
  File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 1189, in det
    raise TypeError, "Illegal input to Fortran routine"
TypeError: Illegal input to Fortran routine

======================================================================
ERROR: testDerivation (unitTests.quadTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 800, in testDerivation
    2*(A*A).trace()
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
    selfA,selfB = self._transformParts()
  File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
    vectors=self.vectors[keep,:]
  File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: invalid index

======================================================================
ERROR: testDerivation (unitTests.outerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 1000, in testDerivation
    out = numpy.outer(Da,Db).reshape((20,3,10,3))
ValueError: total size of new array must be unchanged

======================================================================
FAIL: Doctest: __init__.Mvar.KLdiv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.KLdiv
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1918, in KLdiv

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1941, in __init__.Mvar.KLdiv
Failed example:
    assert deltas.mean**2/deltas.var < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[10]>", line 1, in <module>
        assert deltas.mean**2/deltas.var < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.entropy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.entropy
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1857, in entropy

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1885, in __init__.Mvar.entropy
Failed example:
    assert (deltas.mean**2)/(deltas.var) < (Z**2)   
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[12]>", line 1, in <module>
        assert (deltas.mean**2)/(deltas.var) < (Z**2)
    AssertionError


======================================================================
FAIL: testMatrixMul (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 256, in testMatrixMul
    self.assertTrue( (self.A*self.M)*self.M2.H == self.A*(self.M*self.M2.H) )
AssertionError

======================================================================
FAIL: testDerivation (unitTests.innerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 843, in testDerivation
    self.assertTrue( Var == (numpy.array(Mean -dot)**2).mean() )
AssertionError

======================================================================
FAIL: testAnd (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 518, in testAnd
    self.assertTrue(measured[:self.ndim] == self.A&self.B)
AssertionError

======================================================================
FAIL: testDerivation (unitTests.quadTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 626, in testDerivation
    self.assertTrue( Matrix(dots) == numpy.diag(Da*Da.H) )
AssertionError

======================================================================
FAIL: Doctest: __init__.Mvar.KLdiv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.KLdiv
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1918, in KLdiv

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1941, in __init__.Mvar.KLdiv
Failed example:
    assert deltas.mean**2/deltas.var < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[10]>", line 1, in <module>
        assert deltas.mean**2/deltas.var < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.__gt__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__gt__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1083, in __gt__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1085, in __init__.Mvar.__gt__
Failed example:
    assert (A > Matrix.infs(A.ndim)) == 0
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[0]>", line 1, in <module>
        assert (A > Matrix.infs(A.ndim)) == 0
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1086, in __init__.Mvar.__gt__
Failed example:
    assert (A > -Matrix.infs(A.ndim)) == 1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[1]>", line 1, in <module>
        assert (A > -Matrix.infs(A.ndim)) == 1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1089, in __init__.Mvar.__gt__
Failed example:
    assert Matrix(AV>AV.mean) == 2**-AV.ndim 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[3]>", line 1, in <module>
        assert Matrix(AV>AV.mean) == 2**-AV.ndim
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types


======================================================================
FAIL: Doctest: __init__.Mvar.__lt__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__lt__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1104, in __lt__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1106, in __init__.Mvar.__lt__
Failed example:
    assert (A < Matrix.infs(A.ndim)) == 1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[0]>", line 1, in <module>
        assert (A < Matrix.infs(A.ndim)) == 1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1107, in __init__.Mvar.__lt__
Failed example:
    assert (A < -Matrix.infs(A.ndim)) == 0
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[1]>", line 1, in <module>
        assert (A < -Matrix.infs(A.ndim)) == 0
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1110, in __init__.Mvar.__lt__
Failed example:
    assert Matrix(AV<AV.mean) == 2**-AV.ndim 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[3]>", line 1, in <module>
        assert Matrix(AV<AV.mean) == 2**-AV.ndim
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types


======================================================================
FAIL: Doctest: __init__.Mvar.__mul__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__mul__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 26, in __mul__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 74, in __init__.Mvar.__mul__
Failed example:
    assert (A*M)*M2.H == A*(M*M2.H)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[15]>", line 1, in <module>
        assert (A*M)*M2.H == A*(M*M2.H)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.entropy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.entropy
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1857, in entropy

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1885, in __init__.Mvar.entropy
Failed example:
    assert (deltas.mean**2)/(deltas.var) < (Z**2)   
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[12]>", line 1, in <module>
        assert (deltas.mean**2)/(deltas.var) < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.inner
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.inner
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1756, in inner

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1758, in __init__.Mvar.inner
Failed example:
    assert A.inner(B) == B.inner(A)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.inner[0]>", line 1, in <module>
        assert A.inner(B) == B.inner(A)
    AssertionError


======================================================================
FAIL: testDerivation (unitTests.innerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 843, in testDerivation
    self.assertTrue( Var == (numpy.array(Mean -dot)**2).mean() )
AssertionError

======================================================================
FAIL: testAdd (unitTests.signTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 157, in testAdd
    self.assertTrue( sum(itertools.repeat(-self.A,n),Mvar.zeros(self.A.ndim)) == self.A*(-n) )
AssertionError

======================================================================
FAIL: testPlus (unitTests.signTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 133, in testPlus
    self.assertTrue( self.A+self.A+self.A == 3*self.A )
AssertionError

======================================================================
FAIL: testSub (unitTests.signTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 176, in testSub
    self.assertTrue( self.A-self.A == Mvar(mean=numpy.zeros_like(self.A.mean)) )
AssertionError

======================================================================
FAIL: testIntPowers (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 329, in testIntPowers
    self.assertTrue( self.A.transform(self.N)== self.A.transform()**self.N )
AssertionError

======================================================================
FAIL: testRealPow (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 387, in testRealPow
    self.assertTrue( self.A/self.A**-1 == self.A**2 )
AssertionError

======================================================================
FAIL: testParadoxes (unitTests.inversionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 547, in testParadoxes
    self.assertTrue( (self.A & ~self.A) == Mvar(mean=self.A.mean, vectors=self.A.vectors, var=Matrix.infs) )
AssertionError

======================================================================
FAIL: testSelf (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 570, in testSelf
    self.assertTrue( (self.A & self.A).cov == self.A.cov/2)
AssertionError

======================================================================
FAIL: testMoore (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 469, in testMoore
    self.assertTrue( self.A.chain(b,self.M) == mvar.mooreChain(self.A,b,self.M) )
AssertionError

======================================================================
FAIL: testDerivation (unitTests.quadTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 626, in testDerivation
    self.assertTrue( Matrix(dots) == numpy.diag(Da*Da.H) )
AssertionError

======================================================================
FAIL: Doctest: __init__.Mvar.KLdiv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.KLdiv
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1918, in KLdiv

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1924, in __init__.Mvar.KLdiv
Failed example:
    assert Matrix(A.KLdiv(A)) == 0 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[0]>", line 1, in <module>
        assert Matrix(A.KLdiv(A)) == 0
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1934, in __init__.Mvar.KLdiv
Failed example:
    assert A.entropy(B) == A.KLdiv(B) + A.entropy()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[4]>", line 1, in <module>
        assert A.entropy(B) == A.KLdiv(B) + A.entropy()
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1941, in __init__.Mvar.KLdiv
Failed example:
    assert deltas.mean**2/deltas.var < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[10]>", line 1, in <module>
        assert deltas.mean**2/deltas.var < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.__add__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__add__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1784, in __add__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1814, in __init__.Mvar.__add__
Failed example:
    assert A-A == Mvar(mean=numpy.zeros_like(A.mean))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__add__[5]>", line 1, in <module>
        assert A-A == Mvar(mean=numpy.zeros_like(A.mean))
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.__and__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__and__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1272, in __and__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1306, in __init__.Mvar.__and__
Failed example:
    assert (A & A).cov == A.cov/2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[4]>", line 1, in <module>
        assert (A & A).cov == A.cov/2
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1307, in __init__.Mvar.__and__
Failed example:
    assert (A & A).mean == A.mean
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[5]>", line 1, in <module>
        assert (A & A).mean == A.mean
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.__gt__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__gt__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1083, in __gt__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1085, in __init__.Mvar.__gt__
Failed example:
    assert (A > Matrix.infs(A.ndim)) == 0
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[0]>", line 1, in <module>
        assert (A > Matrix.infs(A.ndim)) == 0
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1086, in __init__.Mvar.__gt__
Failed example:
    assert (A > -Matrix.infs(A.ndim)) == 1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[1]>", line 1, in <module>
        assert (A > -Matrix.infs(A.ndim)) == 1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types


======================================================================
FAIL: Doctest: __init__.Mvar.__invert__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__invert__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1184, in __invert__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1214, in __init__.Mvar.__invert__
Failed example:
    assert (A & ~A) == Mvar(mean=A.mean, vectors=A.vectors, var=Matrix.infs)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[11]>", line 1, in <module>
        assert (A & ~A) == Mvar(mean=A.mean, vectors=A.vectors, var=Matrix.infs)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1241, in __init__.Mvar.__invert__
Failed example:
    assert not numpy.isfinite((A & ~A).var).any()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[17]>", line 1, in <module>
        assert not numpy.isfinite((A & ~A).var).any()
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1245, in __init__.Mvar.__invert__
Failed example:
    assert P==(A & ~A)       
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[20]>", line 1, in <module>
        assert P==(A & ~A)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.__lt__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__lt__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1104, in __lt__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1106, in __init__.Mvar.__lt__
Failed example:
    assert (A < Matrix.infs(A.ndim)) == 1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[0]>", line 1, in <module>
        assert (A < Matrix.infs(A.ndim)) == 1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1107, in __init__.Mvar.__lt__
Failed example:
    assert (A < -Matrix.infs(A.ndim)) == 0
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[1]>", line 1, in <module>
        assert (A < -Matrix.infs(A.ndim)) == 0
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types


======================================================================
FAIL: Doctest: __init__.Mvar.chain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.chain
  File "/home/olpc/personal-projects/mvar/__init__.py", line 769, in chain

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 796, in __init__.Mvar.chain
Failed example:
    assert A.chain(B*M,M) == mooreChain(A,B*M,M)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[3]>", line 1, in <module>
        assert A.chain(B*M,M) == mooreChain(A,B*M,M)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 803, in __init__.Mvar.chain
Failed example:
    assert a.chain(transform=M) == Mvar.fromData(dataA*numpy.hstack([E,M]))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[7]>", line 1, in <module>
        assert a.chain(transform=M) == Mvar.fromData(dataA*numpy.hstack([E,M]))
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 804, in __init__.Mvar.chain
Failed example:
    assert a.chain(transform=M) == Mvar.fromData(numpy.hstack([dataA,dataA*M]))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[8]>", line 1, in <module>
        assert a.chain(transform=M) == Mvar.fromData(numpy.hstack([dataA,dataA*M]))
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.dist2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.dist2
  File "/home/olpc/personal-projects/mvar/__init__.py", line 26, in dist2

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 42, in __init__.Mvar.dist2
Failed example:
    assert Matrix(D1)==D2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.dist2[8]>", line 1, in <module>
        assert Matrix(D1)==D2
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 52, in __init__.Mvar.dist2
Failed example:
    assert (deltas.mean)**2/deltas.var < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.dist2[14]>", line 1, in <module>
        assert (deltas.mean)**2/deltas.var < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.entropy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.entropy
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1857, in entropy

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1865, in __init__.Mvar.entropy
Failed example:
    assert Matrix(numpy.log(1/A.density(S))) == A.entropy(S)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[1]>", line 1, in <module>
        assert Matrix(numpy.log(1/A.density(S))) == A.entropy(S)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1868, in __init__.Mvar.entropy
Failed example:
    assert Matrix(A.entropy(A.copy())) == A.entropy()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[2]>", line 1, in <module>
        assert Matrix(A.entropy(A.copy())) == A.entropy()
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1880, in __init__.Mvar.entropy
Failed example:
    assert (deltas.mean**2)/(deltas.var) < (Z**2)     
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[8]>", line 1, in <module>
        assert (deltas.mean**2)/(deltas.var) < (Z**2)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1885, in __init__.Mvar.entropy
Failed example:
    assert (deltas.mean**2)/(deltas.var) < (Z**2)   
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[12]>", line 1, in <module>
        assert (deltas.mean**2)/(deltas.var) < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.given
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.given
  File "/home/olpc/personal-projects/mvar/__init__.py", line 886, in given

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 897, in __init__.Mvar.given
Failed example:
    a = A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[0]>", line 1, in <module>
        a = A.given(index=0,value=1)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 961, in given
        vectors=vectors,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 338, in __init__
        [1  ,mean   ],
      File "/home/olpc/personal-projects/mvar/helpers.py", line 170, in autostack
        for row in rows
      File "/usr/lib/python2.6/dist-packages/numpy/lib/shape_base.py", line 461, in vstack
        return _nx.concatenate(map(atleast_2d,tup),0)
    ValueError: array dimensions must agree except for d_0
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 898, in __init__.Mvar.given
Failed example:
    assert a.mean[:,0]==1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[1]>", line 1, in <module>
        assert a.mean[:,0]==1
    NameError: name 'a' is not defined
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 899, in __init__.Mvar.given
Failed example:
    assert a.vectors[:,0]==numpy.zeros
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[2]>", line 1, in <module>
        assert a.vectors[:,0]==numpy.zeros
    NameError: name 'a' is not defined
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 924, in __init__.Mvar.given
Failed example:
    a[0]=1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[13]>", line 1, in <module>
        a[0]=1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 972, in __setitem__
        self.copy(self.given(index,value))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 961, in given
        vectors=vectors,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 338, in __init__
        [1  ,mean   ],
      File "/home/olpc/personal-projects/mvar/helpers.py", line 170, in autostack
        for row in rows
      File "/usr/lib/python2.6/dist-packages/numpy/lib/shape_base.py", line 461, in vstack
        return _nx.concatenate(map(atleast_2d,tup),0)
    ValueError: array dimensions must agree except for d_0
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 925, in __init__.Mvar.given
Failed example:
    assert a==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[14]>", line 1, in <module>
        assert a==A.given(index=0,value=1)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 961, in given
        vectors=vectors,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 338, in __init__
        [1  ,mean   ],
      File "/home/olpc/personal-projects/mvar/helpers.py", line 170, in autostack
        for row in rows
      File "/usr/lib/python2.6/dist-packages/numpy/lib/shape_base.py", line 461, in vstack
        return _nx.concatenate(map(atleast_2d,tup),0)
    ValueError: array dimensions must agree except for d_0


======================================================================
FAIL: Doctest: __init__.Mvar.transform
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.transform
  File "/home/olpc/personal-projects/mvar/__init__.py", line 571, in transform

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 581, in __init__.Mvar.transform
Failed example:
    assert A.transform(N)== A.transform()**N  
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.transform[6]>", line 1, in <module>
        assert A.transform(N)== A.transform()**N
    AssertionError


======================================================================
FAIL: Doctest: __init__.givenVector
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.givenVector
  File "/home/olpc/personal-projects/mvar/__init__.py", line 2085, in givenVector

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 2090, in __init__.givenVector
Failed example:
    assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.givenVector[0]>", line 1, in <module>
        assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 961, in given
        vectors=vectors,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 338, in __init__
        [1  ,mean   ],
      File "/home/olpc/personal-projects/mvar/helpers.py", line 170, in autostack
        for row in rows
      File "/usr/lib/python2.6/dist-packages/numpy/lib/shape_base.py", line 461, in vstack
        return _nx.concatenate(map(atleast_2d,tup),0)
    ValueError: array dimensions must agree except for d_0


======================================================================
FAIL: testAnd (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 518, in testAnd
    self.assertTrue(measured[:self.ndim] == self.A&self.B)
AssertionError

======================================================================
FAIL: testMoore (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 469, in testMoore
    self.assertTrue( self.A.chain(b,self.M) == mvar.mooreChain(self.A,b,self.M) )
AssertionError

======================================================================
FAIL: testStacks (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 484, in testStacks
    dataA*numpy.hstack([self.E,self.M])
AssertionError

======================================================================
FAIL: Doctest: __init__.Mvar.KLdiv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.KLdiv
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1918, in KLdiv

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1941, in __init__.Mvar.KLdiv
Failed example:
    assert deltas.mean**2/deltas.var < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[10]>", line 1, in <module>
        assert deltas.mean**2/deltas.var < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.chain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.chain
  File "/home/olpc/personal-projects/mvar/__init__.py", line 769, in chain

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 796, in __init__.Mvar.chain
Failed example:
    assert A.chain(B*M,M) == mooreChain(A,B*M,M)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[3]>", line 1, in <module>
        assert A.chain(B*M,M) == mooreChain(A,B*M,M)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 803, in __init__.Mvar.chain
Failed example:
    assert a.chain(transform=M) == Mvar.fromData(dataA*numpy.hstack([E,M]))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[7]>", line 1, in <module>
        assert a.chain(transform=M) == Mvar.fromData(dataA*numpy.hstack([E,M]))
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 804, in __init__.Mvar.chain
Failed example:
    assert a.chain(transform=M) == Mvar.fromData(numpy.hstack([dataA,dataA*M]))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[8]>", line 1, in <module>
        assert a.chain(transform=M) == Mvar.fromData(numpy.hstack([dataA,dataA*M]))
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.entropy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.entropy
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1857, in entropy

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1885, in __init__.Mvar.entropy
Failed example:
    assert (deltas.mean**2)/(deltas.var) < (Z**2)   
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[12]>", line 1, in <module>
        assert (deltas.mean**2)/(deltas.var) < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.KLdiv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.KLdiv
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1918, in KLdiv

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1924, in __init__.Mvar.KLdiv
Failed example:
    assert Matrix(A.KLdiv(A)) == 0 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[0]>", line 1, in <module>
        assert Matrix(A.KLdiv(A)) == 0
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1951, in KLdiv
        numpy.log(other.det()/self.det())-
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1927, in __init__.Mvar.KLdiv
Failed example:
    assert A.KLdiv(B) > 0
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[1]>", line 1, in <module>
        assert A.KLdiv(B) > 0
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1951, in KLdiv
        numpy.log(other.det()/self.det())-
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1931, in __init__.Mvar.KLdiv
Failed example:
    assert Matrix(A.KLdiv(B)) == (A*m).KLdiv(B*m)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[3]>", line 1, in <module>
        assert Matrix(A.KLdiv(B)) == (A*m).KLdiv(B*m)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1951, in KLdiv
        numpy.log(other.det()/self.det())-
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1934, in __init__.Mvar.KLdiv
Failed example:
    assert A.entropy(B) == A.KLdiv(B) + A.entropy()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[4]>", line 1, in <module>
        assert A.entropy(B) == A.KLdiv(B) + A.entropy()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1907, in entropy
        baseE+=self.KLdiv(data)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1951, in KLdiv
        numpy.log(other.det()/self.det())-
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1939, in __init__.Mvar.KLdiv
Failed example:
    deltas = Mvar.fromData(A.entropy(b) - (A.KLdiv(B) + A.entropy()))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[8]>", line 1, in <module>
        deltas = Mvar.fromData(A.entropy(b) - (A.KLdiv(B) + A.entropy()))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1951, in KLdiv
        numpy.log(other.det()/self.det())-
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1940, in __init__.Mvar.KLdiv
Failed example:
    deltas.var/=N
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[9]>", line 1, in <module>
        deltas.var/=N
    NameError: name 'deltas' is not defined
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1941, in __init__.Mvar.KLdiv
Failed example:
    assert deltas.mean**2/deltas.var < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[10]>", line 1, in <module>
        assert deltas.mean**2/deltas.var < (Z**2)
    NameError: name 'deltas' is not defined


======================================================================
FAIL: Doctest: __init__.Mvar.__and__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__and__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1272, in __and__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1313, in __init__.Mvar.__and__
Failed example:
    if not (A.flat or B.flat):
        assert A & B == wiki(A,B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[6]>", line 2, in <module>
        assert A & B == wiki(A,B)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 2078, in wiki
        Kk=P.cov*Sk.I
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 519, in getI
        return asmatrix(func(self))
      File "/usr/lib/python2.6/dist-packages/scipy/linalg/basic.py", line 366, in inv
        lu,piv,info = getrf(a1,overwrite_a=overwrite_a)
    ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)


======================================================================
FAIL: Doctest: __init__.Mvar.__gt__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__gt__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1083, in __gt__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1085, in __init__.Mvar.__gt__
Failed example:
    assert (A > Matrix.infs(A.ndim)) == 0
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[0]>", line 1, in <module>
        assert (A > Matrix.infs(A.ndim)) == 0
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 205, in mvstdnormcdf
        error, cdfvalue, inform = mvndst(lower,upper,infin,correl,**kwds)
    error: failed in converting 2nd argument `upper' of mvn.mvndst to C/Fortran array
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1086, in __init__.Mvar.__gt__
Failed example:
    assert (A > -Matrix.infs(A.ndim)) == 1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[1]>", line 1, in <module>
        assert (A > -Matrix.infs(A.ndim)) == 1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 205, in mvstdnormcdf
        error, cdfvalue, inform = mvndst(lower,upper,infin,correl,**kwds)
    error: failed in converting 2nd argument `upper' of mvn.mvndst to C/Fortran array
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1089, in __init__.Mvar.__gt__
Failed example:
    assert Matrix(AV>AV.mean) == 2**-AV.ndim 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[3]>", line 1, in <module>
        assert Matrix(AV>AV.mean) == 2**-AV.ndim
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 205, in mvstdnormcdf
        error, cdfvalue, inform = mvndst(lower,upper,infin,correl,**kwds)
    error: failed in converting 2nd argument `upper' of mvn.mvndst to C/Fortran array


======================================================================
FAIL: Doctest: __init__.Mvar.__lt__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__lt__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1104, in __lt__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1106, in __init__.Mvar.__lt__
Failed example:
    assert (A < Matrix.infs(A.ndim)) == 1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[0]>", line 1, in <module>
        assert (A < Matrix.infs(A.ndim)) == 1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 205, in mvstdnormcdf
        error, cdfvalue, inform = mvndst(lower,upper,infin,correl,**kwds)
    error: failed in converting 2nd argument `upper' of mvn.mvndst to C/Fortran array
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1107, in __init__.Mvar.__lt__
Failed example:
    assert (A < -Matrix.infs(A.ndim)) == 0
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[1]>", line 1, in <module>
        assert (A < -Matrix.infs(A.ndim)) == 0
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 205, in mvstdnormcdf
        error, cdfvalue, inform = mvndst(lower,upper,infin,correl,**kwds)
    error: failed in converting 2nd argument `upper' of mvn.mvndst to C/Fortran array
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1110, in __init__.Mvar.__lt__
Failed example:
    assert Matrix(AV<AV.mean) == 2**-AV.ndim 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[3]>", line 1, in <module>
        assert Matrix(AV<AV.mean) == 2**-AV.ndim
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 205, in mvstdnormcdf
        error, cdfvalue, inform = mvndst(lower,upper,infin,correl,**kwds)
    error: failed in converting 2nd argument `upper' of mvn.mvndst to C/Fortran array


======================================================================
FAIL: Doctest: __init__.Mvar.__mul__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__mul__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 26, in __mul__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 36, in __init__.Mvar.__mul__
Failed example:
    assert isinstance(A*B,Mvar)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[0]>", line 1, in <module>
        assert isinstance(A*B,Mvar)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 83, in __init__.Mvar.__mul__
Failed example:
    assert am.shape != ma.shape or ma != am
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[19]>", line 1, in <module>
        assert am.shape != ma.shape or ma != am
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 94, in __init__.Mvar.__mul__
Failed example:
    assert A*(B+C)!=A*B+A*C
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[24]>", line 1, in <module>
        assert A*(B+C)!=A*B+A*C
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 103, in __init__.Mvar.__mul__
Failed example:
    assert A*(B**0+B**0) == A*(2*B**0)   #here the mean is stretched to sqrt(2) times 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[26]>", line 1, in <module>
        assert A*(B**0+B**0) == A*(2*B**0)   #here the mean is stretched to sqrt(2) times
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 106, in __init__.Mvar.__mul__
Failed example:
    assert (A*B**0 + A*B**0).cov == (2*A*B**0).cov 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[28]>", line 1, in <module>
        assert (A*B**0 + A*B**0).cov == (2*A*B**0).cov
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 107, in __init__.Mvar.__mul__
Failed example:
    assert (A*B**0 + A*B**0).mean != (2*A*B**0).mean
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[29]>", line 1, in <module>
        assert (A*B**0 + A*B**0).mean != (2*A*B**0).mean
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 116, in __init__.Mvar.__mul__
Failed example:
    assert A/m == A*(m**(-1))            
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[31]>", line 1, in <module>
        assert A/m == A*(m**(-1))
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 303, in __pow__
        return matrix_power(self, other)
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 130, in matrix_power
        M = inv(M)
      File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 355, in inv
        return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
      File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 258, in solve
        return wrap(b.transpose().astype(result_t))
    ValueError: On entry to ZGESV parameter number 4 had an illegal value
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 117, in __init__.Mvar.__mul__
Failed example:
    assert A/B == A*(B**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[32]>", line 1, in <module>
        assert A/B == A*(B**(-1))
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index


======================================================================
FAIL: Doctest: __init__.Mvar.__pow__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__pow__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1349, in __pow__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1384, in __init__.Mvar.__pow__
Failed example:
    assert A**0*A==A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[6]>", line 1, in <module>
        assert A**0*A==A
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1385, in __init__.Mvar.__pow__
Failed example:
    assert A*A**0==A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[7]>", line 1, in <module>
        assert A*A**0==A
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1386, in __init__.Mvar.__pow__
Failed example:
    if not A.flat:
        assert A**0 == A**(-1)*A
        assert A**0 == A*A**(-1)
        assert A**0 == A/A 
        assert A/A**-1 == A**2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[8]>", line 2, in <module>
        assert A**0 == A**(-1)*A
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1395, in __init__.Mvar.__pow__
Failed example:
    if ((not A.flat) or (k1>=0 and k1>=0)):
        assert (A**k1)*(A**k2)==A**(k1+k2) 
        assert A**k1/A**k2==A**(k1-k2) 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[11]>", line 2, in <module>
        assert (A**k1)*(A**k2)==A**(k1+k2)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1414, in __init__.Mvar.__pow__
Failed example:
    assert (A*B).cov == (A*B.transform()+B*A.transform()).cov/2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[15]>", line 1, in <module>
        assert (A*B).cov == (A*B.transform()+B*A.transform()).cov/2
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1416, in __init__.Mvar.__pow__
Failed example:
    assert (A*B).mean == (A*B.transform()+B*A.transform()).mean/2 or (A.flat or B.flat)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[16]>", line 1, in <module>
        assert (A*B).mean == (A*B.transform()+B*A.transform()).mean/2 or (A.flat or B.flat)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1419, in __init__.Mvar.__pow__
Failed example:
    assert A**2==A*A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[18]>", line 1, in <module>
        assert A**2==A*A
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index


======================================================================
FAIL: Doctest: __init__.Mvar.__rmul__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__rmul__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 26, in __rmul__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 43, in __init__.Mvar.__rmul__
Failed example:
    assert A*A==A**2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[3]>", line 1, in <module>
        assert A*A==A**2
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 63, in __init__.Mvar.__rmul__
Failed example:
    assert A/B == A*(B**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[7]>", line 1, in <module>
        assert A/B == A*(B**(-1))
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 64, in __init__.Mvar.__rmul__
Failed example:
    assert A/m == A*(m**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[8]>", line 1, in <module>
        assert A/m == A*(m**(-1))
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 303, in __pow__
        return matrix_power(self, other)
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 130, in matrix_power
        M = inv(M)
      File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 355, in inv
        return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
      File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 258, in solve
        return wrap(b.transpose().astype(result_t))
    ValueError: On entry to ZGESV parameter number 4 had an illegal value


======================================================================
FAIL: Doctest: __init__.Mvar._mvarMul
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar._mvarMul
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1678, in _mvarMul

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1684, in __init__.Mvar._mvarMul
Failed example:
    assert A*A==A**2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._mvarMul[0]>", line 1, in <module>
        assert A*A==A**2
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1685, in __init__.Mvar._mvarMul
Failed example:
    if not A.flat:
        assert A*A==A*A.transform()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._mvarMul[1]>", line 2, in <module>
        assert A*A==A*A.transform()
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1687, in __init__.Mvar._mvarMul
Failed example:
    assert A*B == B*A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._mvarMul[2]>", line 1, in <module>
        assert A*B == B*A
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index


======================================================================
FAIL: Doctest: __init__.Mvar._transformParts
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar._transformParts
  File "/home/olpc/personal-projects/mvar/__init__.py", line 548, in _transformParts

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 554, in __init__.Mvar._transformParts
Failed example:
    parts = A._transformParts(N) 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._transformParts[1]>", line 1, in <module>
        parts = A._transformParts(N)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 555, in __init__.Mvar._transformParts
Failed example:
    assert parts[0]*parts[1] == A.transform(N)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._transformParts[2]>", line 1, in <module>
        assert parts[0]*parts[1] == A.transform(N)
    NameError: name 'parts' is not defined


======================================================================
FAIL: Doctest: __init__.Mvar.det
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.det
  File "/home/olpc/personal-projects/mvar/__init__.py", line 699, in det

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 705, in __init__.Mvar.det
Failed example:
    assert Matrix(A.det())== numpy.linalg.det(A.cov)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.det[0]>", line 1, in <module>
        assert Matrix(A.det())== numpy.linalg.det(A.cov)
      File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 1189, in det
        raise TypeError, "Illegal input to Fortran routine"
    TypeError: Illegal input to Fortran routine


======================================================================
FAIL: Doctest: __init__.Mvar.dist2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.dist2
  File "/home/olpc/personal-projects/mvar/__init__.py", line 26, in dist2

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 52, in __init__.Mvar.dist2
Failed example:
    assert (deltas.mean)**2/deltas.var < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.dist2[14]>", line 1, in <module>
        assert (deltas.mean)**2/deltas.var < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.entropy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.entropy
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1857, in entropy

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1868, in __init__.Mvar.entropy
Failed example:
    assert Matrix(A.entropy(A.copy())) == A.entropy()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[2]>", line 1, in <module>
        assert Matrix(A.entropy(A.copy())) == A.entropy()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1907, in entropy
        baseE+=self.KLdiv(data)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1951, in KLdiv
        numpy.log(other.det()/self.det())-
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1880, in __init__.Mvar.entropy
Failed example:
    assert (deltas.mean**2)/(deltas.var) < (Z**2)     
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[8]>", line 1, in <module>
        assert (deltas.mean**2)/(deltas.var) < (Z**2)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1883, in __init__.Mvar.entropy
Failed example:
    deltas = Mvar.fromData(A.entropy(b)-A.entropy(B))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[10]>", line 1, in <module>
        deltas = Mvar.fromData(A.entropy(b)-A.entropy(B))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1907, in entropy
        baseE+=self.KLdiv(data)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1951, in KLdiv
        numpy.log(other.det()/self.det())-
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1885, in __init__.Mvar.entropy
Failed example:
    assert (deltas.mean**2)/(deltas.var) < (Z**2)   
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[12]>", line 1, in <module>
        assert (deltas.mean**2)/(deltas.var) < (Z**2)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1889, in __init__.Mvar.entropy
Failed example:
    assert Matrix((A*m).entropy()) == A.entropy()+numpy.log(abs(m.det()))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[14]>", line 1, in <module>
        assert Matrix((A*m).entropy()) == A.entropy()+numpy.log(abs(m.det()))
      File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 1189, in det
        raise TypeError, "Illegal input to Fortran routine"
    TypeError: Illegal input to Fortran routine


======================================================================
FAIL: Doctest: __init__.Mvar.given
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.given
  File "/home/olpc/personal-projects/mvar/__init__.py", line 886, in given

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 897, in __init__.Mvar.given
Failed example:
    a = A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[0]>", line 1, in <module>
        a = A.given(index=0,value=1)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 929, in given
        fixed=binindex(index,self.ndim)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 2162, in binindex
        binindex[index]=True
    IndexError: index out of bounds
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 898, in __init__.Mvar.given
Failed example:
    assert a.mean[:,0]==1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[1]>", line 1, in <module>
        assert a.mean[:,0]==1
    NameError: name 'a' is not defined
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 899, in __init__.Mvar.given
Failed example:
    assert a.vectors[:,0]==numpy.zeros
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[2]>", line 1, in <module>
        assert a.vectors[:,0]==numpy.zeros
    NameError: name 'a' is not defined
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 924, in __init__.Mvar.given
Failed example:
    a[0]=1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[13]>", line 1, in <module>
        a[0]=1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 972, in __setitem__
        self.copy(self.given(index,value))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 929, in given
        fixed=binindex(index,self.ndim)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 2162, in binindex
        binindex[index]=True
    IndexError: index out of bounds
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 925, in __init__.Mvar.given
Failed example:
    assert a==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[14]>", line 1, in <module>
        assert a==A.given(index=0,value=1)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 929, in given
        fixed=binindex(index,self.ndim)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 2162, in binindex
        binindex[index]=True
    IndexError: index out of bounds


======================================================================
FAIL: Doctest: __init__.Mvar.inner
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.inner
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1756, in inner

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1758, in __init__.Mvar.inner
Failed example:
    assert A.inner(B) == B.inner(A)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.inner[0]>", line 1, in <module>
        assert A.inner(B) == B.inner(A)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1769, in inner
        (other*self.mean.H).trace() +
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index


======================================================================
FAIL: Doctest: __init__.Mvar.outer
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.outer
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1777, in outer

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1779, in __init__.Mvar.outer
Failed example:
    assert(numpy.trace(A.outer(B))) == A.inner(B).mean
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.outer[0]>", line 1, in <module>
        assert(numpy.trace(A.outer(B))) == A.inner(B).mean
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1769, in inner
        (other*self.mean.H).trace() +
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index


======================================================================
FAIL: Doctest: __init__.Mvar.sample
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.sample
  File "/home/olpc/personal-projects/mvar/__init__.py", line 633, in sample

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 650, in __init__.Mvar.sample
Failed example:
    divergence = [m.KLdiv(A) for m in mvars]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.sample[6]>", line 1, in <module>
        divergence = [m.KLdiv(A) for m in mvars]
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1951, in KLdiv
        numpy.log(other.det()/self.det())-
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 651, in __init__.Mvar.sample
Failed example:
    assert Matrix(divergence) == sorted(divergence)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.sample[7]>", line 1, in <module>
        assert Matrix(divergence) == sorted(divergence)
    NameError: name 'divergence' is not defined


======================================================================
FAIL: Doctest: __init__.Mvar.trace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.trace
  File "/home/olpc/personal-projects/mvar/__init__.py", line 730, in trace

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 741, in __init__.Mvar.trace
Failed example:
    assert Matrix((A*B).trace()) == (B*A).trace()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.trace[3]>", line 1, in <module>
        assert Matrix((A*B).trace()) == (B*A).trace()
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 742, in __init__.Mvar.trace
Failed example:
    assert Matrix((A.cov*B.cov).trace()) == (A*B).trace() 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.trace[4]>", line 1, in <module>
        assert Matrix((A.cov*B.cov).trace()) == (A*B).trace()
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index


======================================================================
FAIL: Doctest: __init__.Mvar.transform
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.transform
  File "/home/olpc/personal-projects/mvar/__init__.py", line 571, in transform

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 581, in __init__.Mvar.transform
Failed example:
    assert A.transform(N)== A.transform()**N  
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.transform[6]>", line 1, in <module>
        assert A.transform(N)== A.transform()**N
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 303, in __pow__
        return matrix_power(self, other)
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 130, in matrix_power
        M = inv(M)
      File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 355, in inv
        return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
      File "/usr/lib/python2.6/dist-packages/numpy/linalg/linalg.py", line 258, in solve
        return wrap(b.transpose().astype(result_t))
    ValueError: On entry to DGESV parameter number 4 had an illegal value
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 585, in __init__.Mvar.transform
Failed example:
    assert (A*B.transform() + B*A.transform()).cov/2 == (A*B).cov
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.transform[8]>", line 1, in <module>
        assert (A*B.transform() + B*A.transform()).cov/2 == (A*B).cov
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index


======================================================================
FAIL: Doctest: __init__.fromMvarOffset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.fromMvarOffset
  File "/home/olpc/personal-projects/mvar/__init__.py", line 140, in fromMvarOffset

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 144, in __init__.fromMvarOffset
Failed example:
    a=A[0]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.fromMvarOffset[0]>", line 1, in <module>
        a=A[0]
      File "/home/olpc/personal-projects/mvar/__init__.py", line 984, in __getitem__
        mean=self.mean[:,index],
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 145, in __init__.fromMvarOffset
Failed example:
    assert fromData(a,mean=0).mean == Matrix.zeros
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.fromMvarOffset[1]>", line 1, in <module>
        assert fromData(a,mean=0).mean == Matrix.zeros
    NameError: name 'a' is not defined
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 146, in __init__.fromMvarOffset
Failed example:
    assert fromData(a,mean=0).cov == a.cov+a.mean.H*a.mean
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.fromMvarOffset[2]>", line 1, in <module>
        assert fromData(a,mean=0).cov == a.cov+a.mean.H*a.mean
    NameError: name 'a' is not defined


======================================================================
FAIL: Doctest: __init__.givenVector
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.givenVector
  File "/home/olpc/personal-projects/mvar/__init__.py", line 2085, in givenVector

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 2090, in __init__.givenVector
Failed example:
    assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.givenVector[0]>", line 1, in <module>
        assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 2092, in givenVector
        fixed=binindex(index,self.ndim)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 2162, in binindex
        binindex[index]=True
    IndexError: index out of bounds


======================================================================
FAIL: Doctest: __init__.wiki
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.wiki
  File "/home/olpc/personal-projects/mvar/__init__.py", line 2062, in wiki

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 2068, in __init__.wiki
Failed example:
    if not (A.flat or B.flat):    
        assert A**-1 == A*A**-2
        assert A & B == (A*A**-2+B*B**-2)**-1

        D = A*(A.cov)**(-1) + B*(B.cov)**(-1)
        assert wiki(A,B) == D*(D.cov)**(-1)
        assert A & B == wiki(A,B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.wiki[0]>", line 2, in <module>
        assert A**-1 == A*A**-2
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1692, in _mvarMul
        selfA,selfB = self._transformParts()
      File "/home/olpc/personal-projects/mvar/__init__.py", line 566, in _transformParts
        vectors=self.vectors[keep,:]
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 265, in __getitem__
        out = N.ndarray.__getitem__(self, index)
    IndexError: invalid index


======================================================================
FAIL: testDerivation (unitTests.innerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 843, in testDerivation
    self.assertTrue( Var == (numpy.array(Mean -dot)**2).mean() )
AssertionError

======================================================================
FAIL: testDerivation (unitTests.quadTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 626, in testDerivation
    self.assertTrue( Matrix(dots) == numpy.diag(Da*Da.H) )
AssertionError

======================================================================
FAIL: Doctest: __init__.Mvar.KLdiv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.KLdiv
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1918, in KLdiv

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1941, in __init__.Mvar.KLdiv
Failed example:
    assert deltas.mean**2/deltas.var < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[10]>", line 1, in <module>
        assert deltas.mean**2/deltas.var < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.__gt__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__gt__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1083, in __gt__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1085, in __init__.Mvar.__gt__
Failed example:
    assert (A > Matrix.infs(A.ndim)) == 0
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[0]>", line 1, in <module>
        assert (A > Matrix.infs(A.ndim)) == 0
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1086, in __init__.Mvar.__gt__
Failed example:
    assert (A > -Matrix.infs(A.ndim)) == 1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[1]>", line 1, in <module>
        assert (A > -Matrix.infs(A.ndim)) == 1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1089, in __init__.Mvar.__gt__
Failed example:
    assert Matrix(AV>AV.mean) == 2**-AV.ndim 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__gt__[3]>", line 1, in <module>
        assert Matrix(AV>AV.mean) == 2**-AV.ndim
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1095, in __gt__
        numpy.inf*numpy.ones(self.mean.size)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types


======================================================================
FAIL: Doctest: __init__.Mvar.__lt__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__lt__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1104, in __lt__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1106, in __init__.Mvar.__lt__
Failed example:
    assert (A < Matrix.infs(A.ndim)) == 1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[0]>", line 1, in <module>
        assert (A < Matrix.infs(A.ndim)) == 1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1107, in __init__.Mvar.__lt__
Failed example:
    assert (A < -Matrix.infs(A.ndim)) == 0
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[1]>", line 1, in <module>
        assert (A < -Matrix.infs(A.ndim)) == 0
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1110, in __init__.Mvar.__lt__
Failed example:
    assert Matrix(AV<AV.mean) == 2**-AV.ndim 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__lt__[3]>", line 1, in <module>
        assert Matrix(AV<AV.mean) == 2**-AV.ndim
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1116, in __lt__
        upper,
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1167, in inBox
        return mvs(lower,upper,self.cov)
      File "/home/olpc/personal-projects/mvar/mvncdf.py", line 189, in mvstdnormcdf
        lowinf = np.isneginf(lower)
      File "/usr/lib/python2.6/dist-packages/numpy/lib/ufunclike.py", line 173, in isneginf
        nx.logical_and(nx.isinf(x), nx.signbit(x), y)
    TypeError: function not supported for these types, and can't coerce safely to supported types


======================================================================
FAIL: Doctest: __init__.Mvar.entropy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.entropy
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1857, in entropy

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1885, in __init__.Mvar.entropy
Failed example:
    assert (deltas.mean**2)/(deltas.var) < (Z**2)   
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[12]>", line 1, in <module>
        assert (deltas.mean**2)/(deltas.var) < (Z**2)
    AssertionError


----------------------------------------------------------------------
Ran 684 tests in 186.812s

FAILED (failures=67, errors=27)
