test values: ./runTests.py -nFc --ndim 3
{'ndim': 3, 'flat': (False, False, False), 'dtype': ('c', 'c', 'c'), 'seed': None, 'x': None, 'new': True}
F.F.......F.FFFFFF.F.F...FF.FF.FF..F..F...FFFF.EE...F...E.F.F..FFF..F...F.FFFFFFF.F.FFF...FF.......F.F..FF......FF
======================================================================
ERROR: testGivenScalar (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 430, in testGivenScalar
    a = self.A.given(index=0,value=1)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1002, in given
    vectors=vectors,
  File "/home/olpc/personal-projects/mvar/__init__.py", line 340, in __init__
    [1  ,mean   ],
  File "/home/olpc/personal-projects/mvar/helpers.py", line 170, in autostack
    for row in rows
  File "/usr/lib/python2.6/dist-packages/numpy/lib/shape_base.py", line 461, in vstack
    return _nx.concatenate(map(atleast_2d,tup),0)
ValueError: array dimensions must agree except for d_0

======================================================================
ERROR: testGivenVector (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 453, in testGivenVector
    self.assertTrue( mvar.givenVector(self.A,index=0,value=1)==self.A.given(index=0,value=1) )
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1002, in given
    vectors=vectors,
  File "/home/olpc/personal-projects/mvar/__init__.py", line 340, in __init__
    [1  ,mean   ],
  File "/home/olpc/personal-projects/mvar/helpers.py", line 170, in autostack
    for row in rows
  File "/usr/lib/python2.6/dist-packages/numpy/lib/shape_base.py", line 461, in vstack
    return _nx.concatenate(map(atleast_2d,tup),0)
ValueError: array dimensions must agree except for d_0

======================================================================
ERROR: testAnd (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 516, in testAnd
    measured[self.ndim:]=measurment
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1013, in __setitem__
    self.copy(self.given(index,value))
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1002, in given
    vectors=vectors,
  File "/home/olpc/personal-projects/mvar/__init__.py", line 340, in __init__
    [1  ,mean   ],
  File "/home/olpc/personal-projects/mvar/helpers.py", line 170, in autostack
    for row in rows
  File "/usr/lib/python2.6/dist-packages/numpy/lib/shape_base.py", line 461, in vstack
    return _nx.concatenate(map(atleast_2d,tup),0)
ValueError: array dimensions must agree except for d_0

======================================================================
FAIL: testCov (unitTests.propertyTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 311, in testCov
    self.assertTrue( self.A.cov == self.A.transform()*self.A.transform() )
AssertionError

======================================================================
FAIL: testScaled (unitTests.propertyTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 295, in testScaled
    self.assertTrue( Matrix(helpers.mag2(self.A.scaled))==self.A.var )
AssertionError

======================================================================
FAIL: testDiv (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 272, in testDiv
    self.assertTrue( self.A/self.K1 == self.A*(self.K1**(-1)) )
  File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
    return self*other**(-1)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
    assert numpy.isreal(scalar)
AssertionError

======================================================================
FAIL: testMixedMul (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 252, in testMixedMul
    self.assertTrue( self.K1*self.A*self.M == self.A*self.K1*self.M )
  File "<string>", line 2, in __rmul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __rmul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
    assert numpy.isreal(scalar)
AssertionError

======================================================================
FAIL: testMul (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 206, in testMul
    self.assertTrue( self.A**2==self.A*self.A )
AssertionError

======================================================================
FAIL: testMulTypes (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 201, in testMulTypes
    self.assertTrue( isinstance(self.A*self.K1,Mvar) )
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
    assert numpy.isreal(scalar)
AssertionError

======================================================================
FAIL: testMvarMul (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 218, in testMvarMul
    self.assertTrue( self.A**2==self.A*self.A.transform() )
AssertionError

======================================================================
FAIL: testScalarMul (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 234, in testScalarMul
    self.assertTrue( self.A*(self.K1+self.K2)==self.A*self.K1+self.A*self.K2 )
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
    assert numpy.isreal(scalar)
AssertionError

======================================================================
FAIL: testDerivation (unitTests.innerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 843, in testDerivation
    self.assertTrue( Var == (numpy.array(Mean -dot)**2).mean() )
AssertionError

======================================================================
FAIL: testImag (unitTests.signTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 194, in testImag
    self.assertTrue(A & self.B == Ai & self.B)
AssertionError

======================================================================
FAIL: testNeg (unitTests.signTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 147, in testNeg
    self.assertTrue( 1j*self.A*1j==1j*(1j*self.A) ==-self.A )
  File "<string>", line 2, in __rmul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __rmul__
  File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
    assert numpy.isreal(scalar)
AssertionError

======================================================================
FAIL: testDerivation (unitTests.outerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 1008, in testDerivation
    self.assertTrue( B.outer(A) == Matrix(result).H)
AssertionError

======================================================================
FAIL: testComplexPowers (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 336, in testComplexPowers
    self.assertTrue( (self.A**self.K1).transform()**2 == self.A.transform(self.K1)**2 )
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1476, in __pow__
    assert numpy.isreal(power)
AssertionError

======================================================================
FAIL: testOnePow (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 383, in testOnePow
    self.assertTrue( self.A == (self.A**-1)**-1 )
AssertionError

======================================================================
FAIL: testRealPow (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 386, in testRealPow
    self.assertTrue( self.A*self.A==self.A**2 )
AssertionError

======================================================================
FAIL: testZeroFlat (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 371, in testZeroFlat
    self.assertTrue( self.A**0 == self.A**(-1)*self.A )
AssertionError

======================================================================
FAIL: testZeroPow (unitTests.powerTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 365, in testZeroPow
    self.assertTrue( self.A**0*self.A==self.A )
AssertionError

======================================================================
FAIL: testDoubleNegative (unitTests.inversionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 542, in testDoubleNegative
    self.assertTrue( ~(~self.A&~self.B) == self.A & self.B )
AssertionError

======================================================================
FAIL: testParadoxes (unitTests.inversionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 553, in testParadoxes
    self.assertTrue( self.A == self.A & (self.B & ~self.B) )
AssertionError

======================================================================
FAIL: testKnownValues3 (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 610, in testKnownValues3
    self.assertTrue( (L1&L2).mean==[0,1])
AssertionError

======================================================================
FAIL: testNotFlat (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 576, in testNotFlat
    self.assertTrue( self.A & -self.A == Mvar(mean=numpy.zeros(self.ndim))**-1)
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1074, in __eq__
    """
AssertionError: 
            if the objects have different numbers of dimensions, 
            you're doing something wrong
            

======================================================================
FAIL: testSelf (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 570, in testSelf
    self.assertTrue( (self.A & self.A).cov == self.A.cov/2)
AssertionError

======================================================================
FAIL: testGivenLinear (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 443, in testGivenLinear
    self.assertTrue( (L1&L2).mean==[1,1] )
AssertionError

======================================================================
FAIL: testFromCov (unitTests.creationTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 54, in testFromCov
    self.assertTrue(Mvar.fromCov(self.A.cov,mean=self.A.mean) == self.A)
AssertionError

======================================================================
FAIL: testMoore (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 466, in testMoore
    self.assertTrue( self.A.chain(self.B) == mvar.mooreChain(self.A,self.B) )
AssertionError

======================================================================
FAIL: testDet (unitTests.linalgTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 407, in testDet
    self.assertTrue( Matrix(self.A.det())== numpy.linalg.det(self.A.cov) )
AssertionError

======================================================================
FAIL: testTrace (unitTests.linalgTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 402, in testTrace
    self.assertTrue( Matrix(numpy.trace(self.A.transform(0))) == self.A.shape[0] )
AssertionError

======================================================================
FAIL: testDerivation (unitTests.quadTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olpc/personal-projects/mvar/unitTests.py", line 626, in testDerivation
    self.assertTrue( Matrix(dots) == numpy.diag(Da*Da.H) )
AssertionError

======================================================================
FAIL: Doctest: __init__.Mvar.KLdiv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.KLdiv
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1976, in KLdiv

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1982, in __init__.Mvar.KLdiv
Failed example:
    assert Matrix(A.KLdiv(A)) == 0 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[0]>", line 1, in <module>
        assert Matrix(A.KLdiv(A)) == 0
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1992, in __init__.Mvar.KLdiv
Failed example:
    assert A.entropy(B) == A.KLdiv(B) + A.entropy()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[4]>", line 1, in <module>
        assert A.entropy(B) == A.KLdiv(B) + A.entropy()
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1999, in __init__.Mvar.KLdiv
Failed example:
    assert deltas.mean**2/deltas.var < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[10]>", line 1, in <module>
        assert deltas.mean**2/deltas.var < (Z**2)
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


======================================================================
FAIL: Doctest: __init__.Mvar.__and__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__and__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1313, in __and__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1342, in __init__.Mvar.__and__
Failed example:
    if not A.flat:
        assert A &-A == Mvar(mean=numpy.zeros(ndim))**-1
        assert A &~A == Mvar(mean=numpy.zeros(ndim))**-1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[3]>", line 2, in <module>
        assert A &-A == Mvar(mean=numpy.zeros(ndim))**-1
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1074, in __eq__
        """
    AssertionError: 
                if the objects have different numbers of dimensions, 
                you're doing something wrong
                
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1347, in __init__.Mvar.__and__
Failed example:
    assert (A & A).cov == A.cov/2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[4]>", line 1, in <module>
        assert (A & A).cov == A.cov/2
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1348, in __init__.Mvar.__and__
Failed example:
    assert (A & A).mean == A.mean
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[5]>", line 1, in <module>
        assert (A & A).mean == A.mean
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1354, in __init__.Mvar.__and__
Failed example:
    if not (A.flat or B.flat):
        assert A & B == wiki(A,B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[6]>", line 2, in <module>
        assert A & B == wiki(A,B)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1372, in __init__.Mvar.__and__
Failed example:
    assert (L1&L2).mean==[0,1]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[17]>", line 1, in <module>
        assert (L1&L2).mean==[0,1]
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.__invert__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__invert__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1225, in __invert__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1249, in __init__.Mvar.__invert__
Failed example:
    assert ~(~A&~B) == A & B 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[10]>", line 1, in <module>
        assert ~(~A&~B) == A & B
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1261, in __init__.Mvar.__invert__
Failed example:
    if not B.flat:
        assert A == A & (B & ~B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[13]>", line 2, in <module>
        assert A == A & (B & ~B)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1270, in __init__.Mvar.__invert__
Failed example:
    if not (A.flat or B.flat):
       assert (A&B) & ~B == A & (B&~B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[16]>", line 2, in <module>
        assert (A&B) & ~B == A & (B&~B)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1286, in __init__.Mvar.__invert__
Failed example:
    assert P==(A & ~A)       
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[20]>", line 1, in <module>
        assert P==(A & ~A)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1289, in __init__.Mvar.__invert__
Failed example:
    assert (~A & ~B) == ~(A & B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[21]>", line 1, in <module>
        assert (~A & ~B) == ~(A & B)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.__mul__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__mul__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 27, in __mul__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 38, in __init__.Mvar.__mul__
Failed example:
    assert isinstance(A*M,Mvar)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[1]>", line 1, in <module>
        assert isinstance(A*M,Mvar)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 39, in __init__.Mvar.__mul__
Failed example:
    assert isinstance(M.T*A,Matrix) 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[2]>", line 1, in <module>
        assert isinstance(M.T*A,Matrix)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1732, in _rmatrixMul
        return matrix*self.transform()
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 40, in __init__.Mvar.__mul__
Failed example:
    assert isinstance(A*K1,Mvar)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[3]>", line 1, in <module>
        assert isinstance(A*K1,Mvar)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 41, in __init__.Mvar.__mul__
Failed example:
    assert isinstance(K1*A,Mvar)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[4]>", line 1, in <module>
        assert isinstance(K1*A,Mvar)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 59, in __init__.Mvar.__mul__
Failed example:
    assert (A*(K1*E)).mean == K1*A.mean
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[8]>", line 1, in <module>
        assert (A*(K1*E)).mean == K1*A.mean
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 60, in __init__.Mvar.__mul__
Failed example:
    assert (A*(K1*E)).cov == A.cov*abs(K1)**2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[9]>", line 1, in <module>
        assert (A*(K1*E)).cov == A.cov*abs(K1)**2
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 64, in __init__.Mvar.__mul__
Failed example:
    assert (A*(K1*E)).mean == (A*[K1]).mean
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[10]>", line 1, in <module>
        assert (A*(K1*E)).mean == (A*[K1]).mean
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 65, in __init__.Mvar.__mul__
Failed example:
    assert (A*(K1*E)).cov == (A*[K1]).cov
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[11]>", line 1, in <module>
        assert (A*(K1*E)).cov == (A*[K1]).cov
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 68, in __init__.Mvar.__mul__
Failed example:
    assert K1*A*M == A*K1*M 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[12]>", line 1, in <module>
        assert K1*A*M == A*K1*M
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 69, in __init__.Mvar.__mul__
Failed example:
    assert K1*A*M == A*M*K1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[13]>", line 1, in <module>
        assert K1*A*M == A*M*K1
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 72, in __init__.Mvar.__mul__
Failed example:
    assert (K1*A)*K2 == K1*(A*K2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[14]>", line 1, in <module>
        assert (K1*A)*K2 == K1*(A*K2)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 75, in __init__.Mvar.__mul__
Failed example:
    assert (A*M)*M2.H == A*(M*M2.H)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[15]>", line 1, in <module>
        assert (A*M)*M2.H == A*(M*M2.H)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 76, in __init__.Mvar.__mul__
Failed example:
    assert (M*M2.H)*A == M*(M2.H*A)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[16]>", line 1, in <module>
        assert (M*M2.H)*A == M*(M2.H*A)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1732, in _rmatrixMul
        return matrix*self.transform()
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 82, in __init__.Mvar.__mul__
Failed example:
    am=A.transform()*M
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[17]>", line 1, in <module>
        am=A.transform()*M
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 83, in __init__.Mvar.__mul__
Failed example:
    ma=(A*M).transform()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[18]>", line 1, in <module>
        ma=(A*M).transform()
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 84, in __init__.Mvar.__mul__
Failed example:
    assert am.shape != ma.shape or ma != am
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[19]>", line 1, in <module>
        assert am.shape != ma.shape or ma != am
    NameError: name 'am' is not defined
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 87, in __init__.Mvar.__mul__
Failed example:
    assert (A*M).cov == M.H*A.cov*M
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[20]>", line 1, in <module>
        assert (A*M).cov == M.H*A.cov*M
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 91, in __init__.Mvar.__mul__
Failed example:
    assert A*(K1+K2)==A*K1+A*K2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[22]>", line 1, in <module>
        assert A*(K1+K2)==A*K1+A*K2
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 93, in __init__.Mvar.__mul__
Failed example:
    assert A*(M+M2)!=A*M+A*M2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[23]>", line 1, in <module>
        assert A*(M+M2)!=A*M+A*M2
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 98, in __init__.Mvar.__mul__
Failed example:
    assert A*(E+E) != A*E+A*E
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[25]>", line 1, in <module>
        assert A*(E+E) != A*E+A*E
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 104, in __init__.Mvar.__mul__
Failed example:
    assert A*(B**0+B**0) == A*(2*B**0)   #here the mean is stretched to sqrt(2) times 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[26]>", line 1, in <module>
        assert A*(B**0+B**0) == A*(2*B**0)   #here the mean is stretched to sqrt(2) times
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 117, in __init__.Mvar.__mul__
Failed example:
    assert A/m == A*(m**(-1))            
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[31]>", line 1, in <module>
        assert A/m == A*(m**(-1))
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 119, in __init__.Mvar.__mul__
Failed example:
    assert A/K1 == A*(K1**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[33]>", line 1, in <module>
        assert A/K1 == A*(K1**(-1))
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 123, in __init__.Mvar.__mul__
Failed example:
    assert K1/A == K1*(A**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[34]>", line 1, in <module>
        assert K1/A == K1*(A**(-1))
      File "/home/olpc/personal-projects/mvar/decorate/right.py", line 46, in __rdiv__
        return other*self**(-1)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 124, in __init__.Mvar.__mul__
Failed example:
    assert M.H/A==M.H*(A**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[35]>", line 1, in <module>
        assert M.H/A==M.H*(A**(-1))
      File "/home/olpc/personal-projects/mvar/matrix.py", line 58, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1732, in _rmatrixMul
        return matrix*self.transform()
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned


======================================================================
FAIL: Doctest: __init__.Mvar.__pow__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__pow__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1401, in __pow__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1407, in __init__.Mvar.__pow__
Failed example:
    if not A.flat or k>0:
        assert A**k == A*A.transform(k-1) + Mvar(mean=A.mean-A.mean*A.transform(0)) 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[1]>", line 2, in <module>
        assert A**k == A*A.transform(k-1) + Mvar(mean=A.mean-A.mean*A.transform(0))
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1432, in __init__.Mvar.__pow__
Failed example:
    if not A.flat:
        assert A == (A**-1)**-1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[4]>", line 2, in <module>
        assert A == (A**-1)**-1
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1434, in __init__.Mvar.__pow__
Failed example:
    assert A.mean*A.transform(0) == ((A**-1)**-1).mean
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[5]>", line 1, in <module>
        assert A.mean*A.transform(0) == ((A**-1)**-1).mean
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1436, in __init__.Mvar.__pow__
Failed example:
    assert A**0*A==A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[6]>", line 1, in <module>
        assert A**0*A==A
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1437, in __init__.Mvar.__pow__
Failed example:
    assert A*A**0==A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[7]>", line 1, in <module>
        assert A*A**0==A
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1438, in __init__.Mvar.__pow__
Failed example:
    if not A.flat:
        assert A**0 == A**(-1)*A
        assert A**0 == A*A**(-1)
        assert A**0 == A/A 
        assert A/A**-1 == A**2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[8]>", line 2, in <module>
        assert A**0 == A**(-1)*A
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1447, in __init__.Mvar.__pow__
Failed example:
    if ((not A.flat) or (k1>=0 and k1>=0)):
        assert (A**k1)*(A**k2)==A**(k1+k2) 
        assert A**k1/A**k2==A**(k1-k2) 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[11]>", line 2, in <module>
        assert (A**k1)*(A**k2)==A**(k1+k2)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1458, in __init__.Mvar.__pow__
Failed example:
    assert (A**0).mean == A.mean*(A**-1).transform() if not A.flat else True
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[13]>", line 1, in <module>
        assert (A**0).mean == A.mean*(A**-1).transform() if not A.flat else True
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1461, in __init__.Mvar.__pow__
Failed example:
    assert (A**0).mean == A.mean*A.transform(-1) or A.flat
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[14]>", line 1, in <module>
        assert (A**0).mean == A.mean*A.transform(-1) or A.flat
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1468, in __init__.Mvar.__pow__
Failed example:
    assert (A*B).mean == (A*B.transform()+B*A.transform()).mean/2 or (A.flat or B.flat)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[16]>", line 1, in <module>
        assert (A*B).mean == (A*B.transform()+B*A.transform()).mean/2 or (A.flat or B.flat)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1470, in __init__.Mvar.__pow__
Failed example:
    assert M.H*B==M.H*B.transform()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[17]>", line 1, in <module>
        assert M.H*B==M.H*B.transform()
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1732, in _rmatrixMul
        return matrix*self.transform()
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1471, in __init__.Mvar.__pow__
Failed example:
    assert A**2==A*A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[18]>", line 1, in <module>
        assert A**2==A*A
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1472, in __init__.Mvar.__pow__
Failed example:
    if not A.flat:
        #information is lost if the object is flat.
        assert A**2==A*A.transform()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__pow__[19]>", line 3, in <module>
        assert A**2==A*A.transform()
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.__rmul__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__rmul__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 27, in __rmul__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 33, in __init__.Mvar.__rmul__
Failed example:
    assert K1*A == A*K1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[0]>", line 1, in <module>
        assert K1*A == A*K1
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 37, in __init__.Mvar.__rmul__
Failed example:
    assert isinstance(A*M,Mvar)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[1]>", line 1, in <module>
        assert isinstance(A*M,Mvar)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 38, in __init__.Mvar.__rmul__
Failed example:
    assert isinstance(M.H*A,Matrix)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[2]>", line 1, in <module>
        assert isinstance(M.H*A,Matrix)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1732, in _rmatrixMul
        return matrix*self.transform()
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 44, in __init__.Mvar.__rmul__
Failed example:
    assert A*A==A**2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[3]>", line 1, in <module>
        assert A*A==A**2
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 54, in __init__.Mvar.__rmul__
Failed example:
    assert M.H*A==M.H*A.transform()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[4]>", line 1, in <module>
        assert M.H*A==M.H*A.transform()
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1732, in _rmatrixMul
        return matrix*self.transform()
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 57, in __init__.Mvar.__rmul__
Failed example:
    assert A*K1 == K1*A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[5]>", line 1, in <module>
        assert A*K1 == K1*A
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 65, in __init__.Mvar.__rmul__
Failed example:
    assert A/m == A*(m**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[8]>", line 1, in <module>
        assert A/m == A*(m**(-1))
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 66, in __init__.Mvar.__rmul__
Failed example:
    assert A/K1 == A*(K1**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[9]>", line 1, in <module>
        assert A/K1 == A*(K1**(-1))
      File "/home/olpc/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 71, in __init__.Mvar.__rmul__
Failed example:
    assert K1/A == K1*(A**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[10]>", line 1, in <module>
        assert K1/A == K1*(A**(-1))
      File "/home/olpc/personal-projects/mvar/decorate/right.py", line 46, in __rdiv__
        return other*self**(-1)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 72, in __init__.Mvar.__rmul__
Failed example:
    assert M.H/A==M.H*(A**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[11]>", line 1, in <module>
        assert M.H/A==M.H*(A**(-1))
      File "/home/olpc/personal-projects/mvar/matrix.py", line 58, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1732, in _rmatrixMul
        return matrix*self.transform()
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned


======================================================================
FAIL: Doctest: __init__.Mvar.__vectorMul__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__vectorMul__
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1764, in __vectorMul__

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1767, in __init__.Mvar.__vectorMul__
Failed example:
    assert A+[-1]*A == A+A*(-1*E)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__vectorMul__[1]>", line 1, in <module>
        assert A+[-1]*A == A+A*(-1*E)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned


======================================================================
FAIL: Doctest: __init__.Mvar._matrixMul
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar._matrixMul
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1704, in _matrixMul

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1712, in __init__.Mvar._matrixMul
Failed example:
    assert A*E==A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._matrixMul[0]>", line 1, in <module>
        assert A*E==A
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1713, in __init__.Mvar._matrixMul
Failed example:
    assert (-A)*E==-A 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._matrixMul[1]>", line 1, in <module>
        assert (-A)*E==-A
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1716, in __init__.Mvar._matrixMul
Failed example:
    assert A*(E*K1)== A*[K1]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._matrixMul[2]>", line 1, in <module>
        assert A*(E*K1)== A*[K1]
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1720, in __init__.Mvar._matrixMul
Failed example:
    assert (A*M).cov==M.H*A.cov*M
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._matrixMul[4]>", line 1, in <module>
        assert (A*M).cov==M.H*A.cov*M
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1721, in __init__.Mvar._matrixMul
Failed example:
    assert (A*M).mean==A.mean*M
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._matrixMul[5]>", line 1, in <module>
        assert (A*M).mean==A.mean*M
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned


======================================================================
FAIL: Doctest: __init__.Mvar._mvarMul
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar._mvarMul
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1736, in _mvarMul

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1742, in __init__.Mvar._mvarMul
Failed example:
    assert A*A==A**2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._mvarMul[0]>", line 1, in <module>
        assert A*A==A**2
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1743, in __init__.Mvar._mvarMul
Failed example:
    if not A.flat:
        assert A*A==A*A.transform()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._mvarMul[1]>", line 2, in <module>
        assert A*A==A*A.transform()
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar._scalarMul
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar._scalarMul
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1657, in _scalarMul

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1661, in __init__.Mvar._scalarMul
Failed example:
    assert A*K1 == K1*A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._scalarMul[0]>", line 1, in <module>
        assert A*K1 == K1*A
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1679, in __init__.Mvar._scalarMul
Failed example:
    assert (A*K1).mean==K1*A.mean
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._scalarMul[6]>", line 1, in <module>
        assert (A*K1).mean==K1*A.mean
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1680, in __init__.Mvar._scalarMul
Failed example:
    assert (A*K1).cov== (A.cov)*K1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._scalarMul[7]>", line 1, in <module>
        assert (A*K1).cov== (A.cov)*K1
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1691, in __init__.Mvar._scalarMul
Failed example:
    assert 1j*A*1j==-A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar._scalarMul[10]>", line 1, in <module>
        assert 1j*A*1j==-A
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __rmul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1693, in _scalarMul
        assert numpy.isreal(scalar)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.chain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.chain
  File "/home/olpc/personal-projects/mvar/__init__.py", line 810, in chain

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 824, in __init__.Mvar.chain
Failed example:
    assert A.chain()==A*numpy.hstack([E,E]) 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[0]>", line 1, in <module>
        assert A.chain()==A*numpy.hstack([E,E])
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 829, in __init__.Mvar.chain
Failed example:
    assert ( 
        A*numpy.hstack([E,M])== 
        A.chain(transform=M)
    )
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[1]>", line 2, in <module>
        A*numpy.hstack([E,M])==
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 837, in __init__.Mvar.chain
Failed example:
    assert A.chain(B*M,M) == mooreChain(A,B*M,M)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[3]>", line 1, in <module>
        assert A.chain(B*M,M) == mooreChain(A,B*M,M)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 844, in __init__.Mvar.chain
Failed example:
    assert a.chain(transform=M) == Mvar.fromData(dataA*numpy.hstack([E,M]))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[7]>", line 1, in <module>
        assert a.chain(transform=M) == Mvar.fromData(dataA*numpy.hstack([E,M]))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 865, in chain
        perfect=twice*Transform
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 845, in __init__.Mvar.chain
Failed example:
    assert a.chain(transform=M) == Mvar.fromData(numpy.hstack([dataA,dataA*M]))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[8]>", line 1, in <module>
        assert a.chain(transform=M) == Mvar.fromData(numpy.hstack([dataA,dataA*M]))
      File "/home/olpc/personal-projects/mvar/__init__.py", line 865, in chain
        perfect=twice*Transform
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 847, in __init__.Mvar.chain
Failed example:
    assert a.chain(B*M,M) == a.chain(transform=M)+Mvar.stack(Mvar.zeros(a.ndim),B*M)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.chain[9]>", line 1, in <module>
        assert a.chain(B*M,M) == a.chain(transform=M)+Mvar.stack(Mvar.zeros(a.ndim),B*M)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/olpc/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/olpc/personal-projects/mvar/__init__.py", line 1725, in _matrixMul
        mean=self.mean*matrix,
      File "/usr/lib/python2.6/dist-packages/numpy/core/defmatrix.py", line 290, in __mul__
        return N.dot(self, asmatrix(other))
    ValueError: matrices are not aligned


======================================================================
FAIL: Doctest: __init__.Mvar.det
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.det
  File "/home/olpc/personal-projects/mvar/__init__.py", line 740, in det

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 746, in __init__.Mvar.det
Failed example:
    assert Matrix(A.det())== numpy.linalg.det(A.cov)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.det[0]>", line 1, in <module>
        assert Matrix(A.det())== numpy.linalg.det(A.cov)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.dist2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.dist2
  File "/home/olpc/personal-projects/mvar/__init__.py", line 27, in dist2

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 43, in __init__.Mvar.dist2
Failed example:
    assert Matrix(D1)==D2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.dist2[8]>", line 1, in <module>
        assert Matrix(D1)==D2
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 53, in __init__.Mvar.dist2
Failed example:
    assert (deltas.mean)**2/deltas.var < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.dist2[14]>", line 1, in <module>
        assert (deltas.mean)**2/deltas.var < (Z**2)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.entropy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.entropy
  File "/home/olpc/personal-projects/mvar/__init__.py", line 1915, in entropy

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1926, in __init__.Mvar.entropy
Failed example:
    assert Matrix(A.entropy(A.copy())) == A.entropy()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[2]>", line 1, in <module>
        assert Matrix(A.entropy(A.copy())) == A.entropy()
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1938, in __init__.Mvar.entropy
Failed example:
    assert (deltas.mean**2)/(deltas.var) < (Z**2)     
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[8]>", line 1, in <module>
        assert (deltas.mean**2)/(deltas.var) < (Z**2)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1943, in __init__.Mvar.entropy
Failed example:
    assert (deltas.mean**2)/(deltas.var) < (Z**2)   
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[12]>", line 1, in <module>
        assert (deltas.mean**2)/(deltas.var) < (Z**2)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 1947, in __init__.Mvar.entropy
Failed example:
    assert Matrix((A*m).entropy()) == A.entropy()+numpy.log(abs(m.det()))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[14]>", line 1, in <module>
        assert Matrix((A*m).entropy()) == A.entropy()+numpy.log(abs(m.det()))
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.given
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.given
  File "/home/olpc/personal-projects/mvar/__init__.py", line 927, in given

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 939, in __init__.Mvar.given
Failed example:
    assert a.mean[:,0]==1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[1]>", line 1, in <module>
        assert a.mean[:,0]==1
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 948, in __init__.Mvar.given
Failed example:
    assert (L1&L2).mean==[1,1]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[6]>", line 1, in <module>
        assert (L1&L2).mean==[1,1]
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.inflate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.inflate
  File "/home/olpc/personal-projects/mvar/__init__.py", line 420, in inflate

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 425, in __init__.Mvar.inflate
Failed example:
    if A.shape[0] == A.shape[1]:
        assert A*A.vectors.H*A.vectors==A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.inflate[0]>", line 2, in <module>
        assert A*A.vectors.H*A.vectors==A
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 432, in __init__.Mvar.inflate
Failed example:
    assert A*A.vectors.H*A.vectors==A        
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.inflate[3]>", line 1, in <module>
        assert A*A.vectors.H*A.vectors==A
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.sample
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.sample
  File "/home/olpc/personal-projects/mvar/__init__.py", line 674, in sample

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 692, in __init__.Mvar.sample
Failed example:
    assert Matrix(divergence) == sorted(divergence)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.sample[7]>", line 1, in <module>
        assert Matrix(divergence) == sorted(divergence)
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.square
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.square
  File "/home/olpc/personal-projects/mvar/__init__.py", line 475, in square

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 480, in __init__.Mvar.square
Failed example:
    assert A.vectors*A.vectors.H==Matrix.eye
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.square[0]>", line 1, in <module>
        assert A.vectors*A.vectors.H==Matrix.eye
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.trace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.trace
  File "/home/olpc/personal-projects/mvar/__init__.py", line 771, in trace

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 777, in __init__.Mvar.trace
Failed example:
    assert Matrix(A.trace()) == numpy.trace(A.cov)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.trace[0]>", line 1, in <module>
        assert Matrix(A.trace()) == numpy.trace(A.cov)
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 780, in __init__.Mvar.trace
Failed example:
    assert Matrix((A+B).trace()) == A.trace()+B.trace()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.trace[2]>", line 1, in <module>
        assert Matrix((A+B).trace()) == A.trace()+B.trace()
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 783, in __init__.Mvar.trace
Failed example:
    assert Matrix((A.cov*B.cov).trace()) == (A*B).trace() 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.trace[4]>", line 1, in <module>
        assert Matrix((A.cov*B.cov).trace()) == (A*B).trace()
    AssertionError


======================================================================
FAIL: Doctest: __init__.Mvar.transform
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.transform
  File "/home/olpc/personal-projects/mvar/__init__.py", line 612, in transform

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 617, in __init__.Mvar.transform
Failed example:
    assert A.cov == A.transform()*A.transform()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.transform[2]>", line 1, in <module>
        assert A.cov == A.transform()*A.transform()
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 618, in __init__.Mvar.transform
Failed example:
    assert A.cov == A.transform()**2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.transform[3]>", line 1, in <module>
        assert A.cov == A.transform()**2
    AssertionError
----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 628, in __init__.Mvar.transform
Failed example:
    assert Matrix(numpy.trace(A.transform(0))) == A.shape[0] 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.transform[9]>", line 1, in <module>
        assert Matrix(numpy.trace(A.transform(0))) == A.shape[0]
    AssertionError


======================================================================
FAIL: Doctest: __init__.givenVector
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.givenVector
  File "/home/olpc/personal-projects/mvar/__init__.py", line 2143, in givenVector

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 2148, in __init__.givenVector
Failed example:
    assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.givenVector[0]>", line 1, in <module>
        assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
    AssertionError


======================================================================
FAIL: Doctest: __init__.wiki
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/doctest.py", line 2152, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.wiki
  File "/home/olpc/personal-projects/mvar/__init__.py", line 2120, in wiki

----------------------------------------------------------------------
File "/home/olpc/personal-projects/mvar/__init__.py", line 2126, in __init__.wiki
Failed example:
    if not (A.flat or B.flat):    
        assert A**-1 == A*A**-2
        assert A & B == (A*A**-2+B*B**-2)**-1

        D = A*(A.cov)**(-1) + B*(B.cov)**(-1)
        assert wiki(A,B) == D*(D.cov)**(-1)
        assert A & B == wiki(A,B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.wiki[0]>", line 2, in <module>
        assert A**-1 == A*A**-2
    AssertionError


----------------------------------------------------------------------
Ran 114 tests in 26.037s

FAILED (failures=50, errors=3)
