test values: ./runTests.py -x --ndim 3
{'ndim': 3, 'flat': None, 'seed': None, 'new': False, 'flatness': (False, False, False), 'x': True}
....................................FF.FF.F..........FF.............FF..F......................F.F.F...........FFF....F...........E....................E.F..FFFFF..............F........F...F...F..F.F.........F...F...F...F...........FF.....F.
======================================================================
ERROR: testDiv (unitTests.productTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 260, in testDiv
    self.assertTrue( self.A/self.B == self.A*(self.B**(-1)) )
  File "/home/suki/Tutorials/personal-projects/mvar/decorate/automath.py", line 71, in __div__
    return self*other**(-1)
  File "<string>", line 2, in __mul__
  File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1779, in _mvarMul
    result = (self*mvarA*mvarB+mvar*selfA*selfB)
  File "<string>", line 2, in __mul__
  File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1753, in _matrixMul
    vectors=self.vectors*matrix,
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 363, in __init__
    self.copy(self.square())
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 519, in square
    var=result.var,
  File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 71, in square
    (var,vectors) = _subSquare(vectors,var)
  File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 124, in _subSquare
    (val,vec)=eig(cov)
  File "/usr/lib/pymodules/python2.7/numpy/linalg/linalg.py", line 1187, in eigh
    raise LinAlgError, 'Eigenvalues did not converge'
LinAlgError: Eigenvalues did not converge

======================================================================
ERROR: testRight (unitTests.commuteTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 32, in testRight
    self.assertTrue( self.A/self.B == (self.B**-1)*self.A )
  File "/home/suki/Tutorials/personal-projects/mvar/decorate/automath.py", line 71, in __div__
    return self*other**(-1)
  File "<string>", line 2, in __mul__
  File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1779, in _mvarMul
    result = (self*mvarA*mvarB+mvar*selfA*selfB)
  File "<string>", line 2, in __mul__
  File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 50, in F
    return decorated(*before(*args),**kwargs)
  File "<string>", line 2, in __mul__
  File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 140, in caller
    return found(*args,**kwargs)
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1753, in _matrixMul
    vectors=self.vectors*matrix,
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 363, in __init__
    self.copy(self.square())
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 519, in square
    var=result.var,
  File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 71, in square
    (var,vectors) = _subSquare(vectors,var)
  File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 124, in _subSquare
    (val,vec)=eig(cov)
  File "/usr/lib/pymodules/python2.7/numpy/linalg/linalg.py", line 1187, in eigh
    raise LinAlgError, 'Eigenvalues did not converge'
LinAlgError: Eigenvalues did not converge

======================================================================
FAIL: testParadoxes (unitTests.inversionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 537, in testParadoxes
    self.assertTrue( (self.A & ~self.A) == Mvar(mean=self.A.mean, vectors=self.A.vectors, var=Matrix.infs) )
AssertionError: False is not true

======================================================================
FAIL: testPow (unitTests.inversionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 571, in testPow
    Mvar.zeros(self.A.ndim)**-1
AssertionError: False is not true

======================================================================
FAIL: testKnownValues1 (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 607, in testKnownValues1
    self.assertTrue( (L1&L2).mean==[1,1])
AssertionError: False is not true

======================================================================
FAIL: testKnownValues2 (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 613, in testKnownValues2
    self.assertTrue( (L1&L2).mean==[1,1])
AssertionError: False is not true

======================================================================
FAIL: testNotFlat (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 585, in testNotFlat
    self.assertTrue( self.A & -self.A == Mvar(mean=numpy.zeros(self.ndim))**-1)
AssertionError: False is not true

======================================================================
FAIL: testInfs (unitTests.creationTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 67, in testInfs
    self.assertTrue( inf.mean==Matrix.zeros )
AssertionError: False is not true

======================================================================
FAIL: testZeros (unitTests.creationTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 62, in testZeros
    self.assertTrue( Z**-1 == Mvar.infs)
AssertionError: False is not true

======================================================================
FAIL: __and__ (__init__.Mvar)
Doctest: __init__.Mvar.__and__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__and__
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1358, in __and__

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1387, in __init__.Mvar.__and__
Failed example:
    if not A.flat:
        assert A &-A == Mvar(mean=numpy.zeros(ndim))**-1
        assert A &~A == Mvar(mean=numpy.zeros(ndim))**-1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[3]>", line 2, in <module>
        assert A &-A == Mvar(mean=numpy.zeros(ndim))**-1
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1407, in __init__.Mvar.__and__
Failed example:
    assert (L1&L2).mean==[1,1]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[9]>", line 1, in <module>
        assert (L1&L2).mean==[1,1]
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1412, in __init__.Mvar.__and__
Failed example:
    assert (L1&L2).mean==[2,1]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[13]>", line 1, in <module>
        assert (L1&L2).mean==[2,1]
    AssertionError


======================================================================
FAIL: __eq__ (__init__.Mvar)
Doctest: __init__.Mvar.__eq__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__eq__
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1077, in __eq__

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1107, in __init__.Mvar.__eq__
Failed example:
    assert Mvar.infs(n) == Mvar.infs
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__eq__[8]>", line 1, in <module>
        assert Mvar.infs(n) == Mvar.infs
    AssertionError


======================================================================
FAIL: __invert__ (__init__.Mvar)
Doctest: __init__.Mvar.__invert__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__invert__
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1270, in __invert__

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1300, in __init__.Mvar.__invert__
Failed example:
    assert (A & ~A) == Mvar(mean=A.mean, vectors=A.vectors, var=Matrix.infs)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[11]>", line 1, in <module>
        assert (A & ~A) == Mvar(mean=A.mean, vectors=A.vectors, var=Matrix.infs)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1301, in __init__.Mvar.__invert__
Failed example:
    if not A.flat:
        assert (A & ~A) == Mvar(mean=numpy.zeros(A.ndim))**-1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[12]>", line 2, in <module>
        assert (A & ~A) == Mvar(mean=numpy.zeros(A.ndim))**-1
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1306, in __init__.Mvar.__invert__
Failed example:
    if not B.flat:
        assert A == A & (B & ~B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[13]>", line 2, in <module>
        assert A == A & (B & ~B)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1311, in __init__.Mvar.__invert__
Failed example:
    assert  A &(B & ~B) == A & Mvar(mean=B.mean, vectors=B.vectors, var=Matrix.infs)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[14]>", line 1, in <module>
        assert  A &(B & ~B) == A & Mvar(mean=B.mean, vectors=B.vectors, var=Matrix.infs)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1315, in __init__.Mvar.__invert__
Failed example:
    if not (A.flat or B.flat):
       assert (A&B) & ~B == A & (B&~B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[16]>", line 2, in <module>
        assert (A&B) & ~B == A & (B&~B)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1331, in __init__.Mvar.__invert__
Failed example:
    assert P==(A & ~A)       
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[20]>", line 1, in <module>
        assert P==(A & ~A)
    AssertionError


======================================================================
FAIL: given (__init__.Mvar)
Doctest: __init__.Mvar.given
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.given
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 929, in given

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 976, in __init__.Mvar.given
Failed example:
    assert a==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[17]>", line 1, in <module>
        assert a==A.given(index=0,value=1)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 983, in __init__.Mvar.given
Failed example:
    assert A.given(0,x) == A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[20]>", line 1, in <module>
        assert A.given(0,x) == A
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 986, in __init__.Mvar.given
Failed example:
    !! this is one step from a reverse chain ?
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[21]>", line 1
        !! this is one step from a reverse chain ?
        ^
    SyntaxError: invalid syntax
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 989, in __init__.Mvar.given
Failed example:
    assert a == A.given(index,~A[index]) 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[24]>", line 1, in <module>
        assert a == A.given(index,~A[index])
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 990, in __init__.Mvar.given
Failed example:
    assert a  & A.marginal(index) == A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[25]>", line 1, in <module>
        assert a  & A.marginal(index) == A
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 991, in __init__.Mvar.given
Failed example:
    assert A.given(0).given(0,0) == A.given(0,0)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[26]>", line 1, in <module>
        assert A.given(0).given(0,0) == A.given(0,0)
    AssertionError


======================================================================
FAIL: infs (__init__.Mvar)
Doctest: __init__.Mvar.infs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.infs
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 405, in infs

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 409, in __init__.Mvar.infs
Failed example:
    assert inf.mean==Matrix.zeros
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.infs[2]>", line 1, in <module>
        assert inf.mean==Matrix.zeros
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 413, in __init__.Mvar.infs
Failed example:
    assert inf**-1 == Mvar.zeros
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.infs[6]>", line 1, in <module>
        assert inf**-1 == Mvar.zeros
    AssertionError


======================================================================
FAIL: marginal (__init__.Mvar)
Doctest: __init__.Mvar.marginal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.marginal
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1040, in marginal

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1048, in __init__.Mvar.marginal
Failed example:
    assert reduce(operator.and_,M) == A.diag()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.marginal[3]>", line 1, in <module>
        assert reduce(operator.and_,M) == A.diag()
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1427, in __and__
        Dmean = Plane.__and__(self,other).mean
      File "/home/suki/Tutorials/personal-projects/mvar/plane.py", line 112, in __and__
        Nself=self.getNull()
      File "/home/suki/Tutorials/personal-projects/mvar/plane.py", line 105, in getNull
        return getNull(self.vectors)
      File "/home/suki/Tutorials/personal-projects/mvar/plane.py", line 20, in getNull
        var,vectors = square(vectors)
      File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 71, in square
        (var,vectors) = _subSquare(vectors,var)
      File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 124, in _subSquare
        (val,vec)=eig(cov)
      File "/usr/lib/pymodules/python2.7/numpy/linalg/linalg.py", line 1187, in eigh
        raise LinAlgError, 'Eigenvalues did not converge'
    LinAlgError: Eigenvalues did not converge


======================================================================
FAIL: transform (__init__.Mvar)
Doctest: __init__.Mvar.transform
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.transform
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 612, in transform

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 624, in __init__.Mvar.transform
Failed example:
    assert (A**numpy.real(K1)).transform() == A.transform(numpy.real(K1)) 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.transform[7]>", line 1, in <module>
        assert (A**numpy.real(K1)).transform() == A.transform(numpy.real(K1))
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1520, in __pow__
        mean=self.mean*self.transform(power-1)+dmean,
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 639, in transform
        ),"negative number cannot be raised to a fractional power"
    AssertionError: negative number cannot be raised to a fractional power


======================================================================
FAIL: width (__init__.Mvar)
Doctest: __init__.Mvar.width
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.width
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 789, in width

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 794, in __init__.Mvar.width
Failed example:
    assert Matrix([A[n].var[0] for n in range(A.ndim)]) == A.width()**2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.width[0]>", line 1, in <module>
        assert Matrix([A[n].var[0] for n in range(A.ndim)]) == A.width()**2
    IndexError: index out of bounds
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 796, in __init__.Mvar.width
Failed example:
    assert Matrix(A.corr.diagonal()) == Matrix.ones
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.width[1]>", line 1, in <module>
        assert Matrix(A.corr.diagonal()) == Matrix.ones
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 799, in __init__.Mvar.width
Failed example:
    assert norm.corr == norm.cov
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.width[3]>", line 1, in <module>
        assert norm.corr == norm.cov
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 552, in fget
        return (self/self.width()).cov
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1802, in __vectorMul__
        var=self.var,
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 360, in __init__
        ),'real numbers only'
    AssertionError: real numbers only
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 800, in __init__.Mvar.width
Failed example:
    assert Matrix([norm[n].var[0] for n in range(norm.ndim)]) == Matrix.ones
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.width[4]>", line 1, in <module>
        assert Matrix([norm[n].var[0] for n in range(norm.ndim)]) == Matrix.ones
    AssertionError


======================================================================
FAIL: zeros (__init__.Mvar)
Doctest: __init__.Mvar.zeros
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.zeros
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 390, in zeros

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 397, in __init__.Mvar.zeros
Failed example:
    assert Z**-1 == Mvar.infs
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.zeros[5]>", line 1, in <module>
        assert Z**-1 == Mvar.infs
    AssertionError


======================================================================
FAIL: givenVector (__init__)
Doctest: __init__.givenVector
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.givenVector
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2311, in givenVector

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2316, in __init__.givenVector
Failed example:
    assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.givenVector[0]>", line 1, in <module>
        assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
    AssertionError


======================================================================
FAIL: testDoubleNegative (unitTests.inversionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 532, in testDoubleNegative
    self.assertTrue( ~(~self.A&~self.B) == self.A & self.B )
AssertionError: False is not true

======================================================================
FAIL: testParadoxes (unitTests.inversionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 537, in testParadoxes
    self.assertTrue( (self.A & ~self.A) == Mvar(mean=self.A.mean, vectors=self.A.vectors, var=Matrix.infs) )
AssertionError: False is not true

======================================================================
FAIL: testPow (unitTests.inversionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 571, in testPow
    Mvar.zeros(self.A.ndim)**-1
AssertionError: False is not true

======================================================================
FAIL: testCommutativity (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 576, in testCommutativity
    self.assertTrue( self.A & self.B == self.B & self.A)
AssertionError: False is not true

======================================================================
FAIL: testKnownValues1 (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 607, in testKnownValues1
    self.assertTrue( (L1&L2).mean==[1,1])
AssertionError: False is not true

======================================================================
FAIL: testKnownValues2 (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 613, in testKnownValues2
    self.assertTrue( (L1&L2).mean==[1,1])
AssertionError: False is not true

======================================================================
FAIL: testAnd (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 508, in testAnd
    self.assertTrue(measured[:self.ndim] == self.A&self.B)
AssertionError: False is not true

======================================================================
FAIL: KLdiv (__init__.Mvar)
Doctest: __init__.Mvar.KLdiv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.KLdiv
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2053, in KLdiv

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2072, in __init__.Mvar.KLdiv
Failed example:
    assert Matrix(A.KLdiv(B)) == (A*m).KLdiv(B*m)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[5]>", line 1, in <module>
        assert Matrix(A.KLdiv(B)) == (A*m).KLdiv(B*m)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2098, in __init__.Mvar.KLdiv
Failed example:
    assert KL.dist2() < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[19]>", line 1, in <module>
        assert KL.dist2() < (Z**2)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2105, in __init__.Mvar.KLdiv
Failed example:
    assert KL.dist2() < (Z**2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.KLdiv[25]>", line 1, in <module>
        assert KL.dist2() < (Z**2)
    AssertionError


======================================================================
FAIL: __and__ (__init__.Mvar)
Doctest: __init__.Mvar.__and__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__and__
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1358, in __and__

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1375, in __init__.Mvar.__and__
Failed example:
    assert A & B == B & A 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[0]>", line 1, in <module>
        assert A & B == B & A
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1387, in __init__.Mvar.__and__
Failed example:
    if not A.flat:
        assert A &-A == Mvar(mean=numpy.zeros(ndim))**-1
        assert A &~A == Mvar(mean=numpy.zeros(ndim))**-1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[3]>", line 2, in <module>
        assert A &-A == Mvar(mean=numpy.zeros(ndim))**-1
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1407, in __init__.Mvar.__and__
Failed example:
    assert (L1&L2).mean==[1,1]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[9]>", line 1, in <module>
        assert (L1&L2).mean==[1,1]
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1412, in __init__.Mvar.__and__
Failed example:
    assert (L1&L2).mean==[2,1]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[13]>", line 1, in <module>
        assert (L1&L2).mean==[2,1]
    AssertionError


======================================================================
FAIL: __invert__ (__init__.Mvar)
Doctest: __init__.Mvar.__invert__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__invert__
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1270, in __invert__

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1294, in __init__.Mvar.__invert__
Failed example:
    assert ~(~A&~B) == A & B 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[10]>", line 1, in <module>
        assert ~(~A&~B) == A & B
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1300, in __init__.Mvar.__invert__
Failed example:
    assert (A & ~A) == Mvar(mean=A.mean, vectors=A.vectors, var=Matrix.infs)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[11]>", line 1, in <module>
        assert (A & ~A) == Mvar(mean=A.mean, vectors=A.vectors, var=Matrix.infs)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1301, in __init__.Mvar.__invert__
Failed example:
    if not A.flat:
        assert (A & ~A) == Mvar(mean=numpy.zeros(A.ndim))**-1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[12]>", line 2, in <module>
        assert (A & ~A) == Mvar(mean=numpy.zeros(A.ndim))**-1
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1311, in __init__.Mvar.__invert__
Failed example:
    assert  A &(B & ~B) == A & Mvar(mean=B.mean, vectors=B.vectors, var=Matrix.infs)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[14]>", line 1, in <module>
        assert  A &(B & ~B) == A & Mvar(mean=B.mean, vectors=B.vectors, var=Matrix.infs)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1314, in __init__.Mvar.__invert__
Failed example:
    assert (A&~B) & B == (A&B) & ~B
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[15]>", line 1, in <module>
        assert (A&~B) & B == (A&B) & ~B
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1331, in __init__.Mvar.__invert__
Failed example:
    assert P==(A & ~A)       
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[20]>", line 1, in <module>
        assert P==(A & ~A)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1334, in __init__.Mvar.__invert__
Failed example:
    assert (~A & ~B) == ~(A & B)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[21]>", line 1, in <module>
        assert (~A & ~B) == ~(A & B)
    AssertionError


======================================================================
FAIL: __mul__ (__init__.Mvar)
Doctest: __init__.Mvar.__mul__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__mul__
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 28, in __mul__

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 119, in __init__.Mvar.__mul__
Failed example:
    assert A/B == A*(B**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__mul__[32]>", line 1, in <module>
        assert A/B == A*(B**(-1))
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1779, in _mvarMul
        result = (self*mvarA*mvarB+mvar*selfA*selfB)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1753, in _matrixMul
        vectors=self.vectors*matrix,
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 363, in __init__
        self.copy(self.square())
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 519, in square
        var=result.var,
      File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 71, in square
        (var,vectors) = _subSquare(vectors,var)
      File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 124, in _subSquare
        (val,vec)=eig(cov)
      File "/usr/lib/pymodules/python2.7/numpy/linalg/linalg.py", line 1187, in eigh
        raise LinAlgError, 'Eigenvalues did not converge'
    LinAlgError: Eigenvalues did not converge


======================================================================
FAIL: __rmul__ (__init__.Mvar)
Doctest: __init__.Mvar.__rmul__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__rmul__
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 28, in __rmul__

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 65, in __init__.Mvar.__rmul__
Failed example:
    assert A/B == A*(B**(-1))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__rmul__[7]>", line 1, in <module>
        assert A/B == A*(B**(-1))
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1779, in _mvarMul
        result = (self*mvarA*mvarB+mvar*selfA*selfB)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1753, in _matrixMul
        vectors=self.vectors*matrix,
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 363, in __init__
        self.copy(self.square())
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 519, in square
        var=result.var,
      File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 71, in square
        (var,vectors) = _subSquare(vectors,var)
      File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 124, in _subSquare
        (val,vec)=eig(cov)
      File "/usr/lib/pymodules/python2.7/numpy/linalg/linalg.py", line 1187, in eigh
        raise LinAlgError, 'Eigenvalues did not converge'
    LinAlgError: Eigenvalues did not converge


======================================================================
FAIL: density (__init__.Mvar)
Doctest: __init__.Mvar.density
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.density
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1943, in density

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1959, in __init__.Mvar.density
Failed example:
    assert Matrix(0) == ratio.var()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.density[7]>", line 1, in <module>
        assert Matrix(0) == ratio.var()
    AssertionError


======================================================================
FAIL: entropy (__init__.Mvar)
Doctest: __init__.Mvar.entropy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.entropy
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1964, in entropy

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2026, in __init__.Mvar.entropy
Failed example:
    assert deltas.dist2() < (Z**2)  
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.entropy[23]>", line 1, in <module>
        assert deltas.dist2() < (Z**2)
    AssertionError


======================================================================
FAIL: given (__init__.Mvar)
Doctest: __init__.Mvar.given
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.given
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 929, in given

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 976, in __init__.Mvar.given
Failed example:
    assert a==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[17]>", line 1, in <module>
        assert a==A.given(index=0,value=1)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 983, in __init__.Mvar.given
Failed example:
    assert A.given(0,x) == A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[20]>", line 1, in <module>
        assert A.given(0,x) == A
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 986, in __init__.Mvar.given
Failed example:
    !! this is one step from a reverse chain ?
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[21]>", line 1
        !! this is one step from a reverse chain ?
        ^
    SyntaxError: invalid syntax
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 989, in __init__.Mvar.given
Failed example:
    assert a == A.given(index,~A[index]) 
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[24]>", line 1, in <module>
        assert a == A.given(index,~A[index])
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 990, in __init__.Mvar.given
Failed example:
    assert a  & A.marginal(index) == A
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[25]>", line 1, in <module>
        assert a  & A.marginal(index) == A
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 991, in __init__.Mvar.given
Failed example:
    assert A.given(0).given(0,0) == A.given(0,0)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[26]>", line 1, in <module>
        assert A.given(0).given(0,0) == A.given(0,0)
    AssertionError


======================================================================
FAIL: marginal (__init__.Mvar)
Doctest: __init__.Mvar.marginal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.marginal
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1040, in marginal

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1048, in __init__.Mvar.marginal
Failed example:
    assert reduce(operator.and_,M) == A.diag()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.marginal[3]>", line 1, in <module>
        assert reduce(operator.and_,M) == A.diag()
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1427, in __and__
        Dmean = Plane.__and__(self,other).mean
      File "/home/suki/Tutorials/personal-projects/mvar/plane.py", line 112, in __and__
        Nself=self.getNull()
      File "/home/suki/Tutorials/personal-projects/mvar/plane.py", line 105, in getNull
        return getNull(self.vectors)
      File "/home/suki/Tutorials/personal-projects/mvar/plane.py", line 20, in getNull
        var,vectors = square(vectors)
      File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 71, in square
        (var,vectors) = _subSquare(vectors,var)
      File "/home/suki/Tutorials/personal-projects/mvar/square.py", line 124, in _subSquare
        (val,vec)=eig(cov)
      File "/usr/lib/pymodules/python2.7/numpy/linalg/linalg.py", line 1187, in eigh
        raise LinAlgError, 'Eigenvalues did not converge'
    LinAlgError: Eigenvalues did not converge


======================================================================
FAIL: transform (__init__.Mvar)
Doctest: __init__.Mvar.transform
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.transform
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 612, in transform

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 621, in __init__.Mvar.transform
Failed example:
    assert A.transform(N)== (A**N).transform()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.transform[5]>", line 1, in <module>
        assert A.transform(N)== (A**N).transform()
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 622, in __init__.Mvar.transform
Failed example:
    assert A.transform(N)== A.transform()**N  
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.transform[6]>", line 1, in <module>
        assert A.transform(N)== A.transform()**N
      File "/usr/lib/pymodules/python2.7/numpy/matrixlib/defmatrix.py", line 343, in __pow__
        return matrix_power(self, other)
      File "/usr/lib/pymodules/python2.7/numpy/matrixlib/defmatrix.py", line 171, in matrix_power
        M = inv(M)
      File "/usr/lib/pymodules/python2.7/numpy/linalg/linalg.py", line 445, in inv
        return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
      File "/usr/lib/pymodules/python2.7/numpy/linalg/linalg.py", line 328, in solve
        raise LinAlgError, 'Singular matrix'
    LinAlgError: Singular matrix


======================================================================
FAIL: width (__init__.Mvar)
Doctest: __init__.Mvar.width
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.width
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 789, in width

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 794, in __init__.Mvar.width
Failed example:
    assert Matrix([A[n].var[0] for n in range(A.ndim)]) == A.width()**2
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.width[0]>", line 1, in <module>
        assert Matrix([A[n].var[0] for n in range(A.ndim)]) == A.width()**2
    IndexError: index out of bounds
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 796, in __init__.Mvar.width
Failed example:
    assert Matrix(A.corr.diagonal()) == Matrix.ones
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.width[1]>", line 1, in <module>
        assert Matrix(A.corr.diagonal()) == Matrix.ones
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 799, in __init__.Mvar.width
Failed example:
    assert norm.corr == norm.cov
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.width[3]>", line 1, in <module>
        assert norm.corr == norm.cov
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 552, in fget
        return (self/self.width()).cov
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/automath.py", line 71, in __div__
        return self*other**(-1)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 50, in F
        return decorated(*before(*args),**kwargs)
      File "<string>", line 2, in __mul__
      File "/home/suki/Tutorials/personal-projects/mvar/decorate/__init__.py", line 140, in caller
        return found(*args,**kwargs)
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1802, in __vectorMul__
        var=self.var,
      File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 360, in __init__
        ),'real numbers only'
    AssertionError: real numbers only
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 800, in __init__.Mvar.width
Failed example:
    assert Matrix([norm[n].var[0] for n in range(norm.ndim)]) == Matrix.ones
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.width[4]>", line 1, in <module>
        assert Matrix([norm[n].var[0] for n in range(norm.ndim)]) == Matrix.ones
    AssertionError


======================================================================
FAIL: givenVector (__init__)
Doctest: __init__.givenVector
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.givenVector
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2311, in givenVector

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2316, in __init__.givenVector
Failed example:
    assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.givenVector[0]>", line 1, in <module>
        assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
    AssertionError


----------------------------------------------------------------------
Ran 240 tests in 2.215s

FAILED (failures=36, errors=2)
